var gvjs_jS="border: 0; padding: 0; margin: 0;";gvjs_JE.prototype.UE=gvjs_W(131,function(a){this.ticks=a});gvjs_PE.prototype.UE=gvjs_W(130,function(a){gvjs_PE.o.UE.call(this,a);var b=0;gvjs_s(this.ticks,function(c){c=this.ir(c);b=Math.max(b,gvjs__z(c/this.Mea))},this);this.w8=b});
function gvjs_kS(a,b,c,d,e){gvjs_jm.call(this);this.ia=a;this.da=b;this.Pa=c;this.xL=new gvjs_Ay({hb:gvjs_it,fontSize:d,color:gvjs_Cr,opacity:1,Pb:"",bold:!1,ed:!1,lf:!1});this.Mya=new gvjs_Ay({hb:gvjs_it,fontSize:d,color:gvjs_0o,opacity:1,Pb:"",bold:!1,ed:!1,lf:!1});this.Mxa=new gvjs_Ay({hb:gvjs_it,fontSize:0,color:gvjs_Cr,opacity:1,Pb:"",bold:!1,ed:!1,lf:!1});this.jva=e;this.xg=this.Ta=this.C=null;this.R1=[]}gvjs_m(gvjs_kS,gvjs_jm);gvjs_=gvjs_kS.prototype;gvjs_.yf=function(){return this.Ya};
gvjs_.Mw=function(a){this.Ya=a};gvjs_.xf=function(){return this.Cb};gvjs_.iu=function(a){this.Cb=a};gvjs_.Wa=function(a,b,c){this.ce=a;this.nY=b;this.qu();a=gvjs_lS(this,a);null!=this.OJ&&c?(this.cg=new gvjs_3D([this.OJ],[a],c.duration,c.easing),gvjs_K(this.cg,["begin","animate",gvjs_T],this.Wta,!1,this),gvjs_K(this.cg,gvjs_T,this.Vta,!1,this),this.cg.play(!1)):(this.OJ=a,gvjs_mS(this))};gvjs_.UE=function(a,b){this.Oba=Math.max(1,a);this.SD=Math.max(1,b)};gvjs_.W2=function(a){this.Kz=a};
function gvjs_nS(a,b,c,d){a.R1.push({uf:b,Fl:c,color:d})}gvjs_.setAnimation=function(){};gvjs_.clear=function(){this.qu();gvjs_J(this.Ta);this.Ta=null;gvjs_fm(this)};gvjs_.draw=function(a,b){var c=new gvjs_y(this.da,this.Pa);null==this.Ta?this.Ta=new gvjs_Xq(this.ia,c,a,b):this.Ta.update(c,a);this.Ta.fo(gvjs_q(this.zo,this),a)};
gvjs_.zo=function(){var a=this.Ta.$a(),b=a.Ql(this.da,this.Pa);a.ec(b,gvjs_8t,gvjs_0A);this.C=a;var c=this.xg=a.Sa(!1);a.appendChild(b,c);b=Math.round(.45*Math.min(this.da,this.Pa));var d=this.da/2,e=this.Pa/2;a.ze(d-.5,e-.5,b,gvjs_oS,c);b-=gvjs_oS.Ub;b=Math.round(.9*b);a.ze(d-.5,e-.5,b,gvjs_pS,c);b-=2*gvjs_pS.Ub;var f=.75*b;for(var g=0;g<this.R1.length;g++){var h=this.R1[g],k=gvjs_qS(this,gvjs_lS(this,h.uf)),l=gvjs_qS(this,gvjs_lS(this,h.Fl)),m=new gvjs_hy,n=d+gvjs_1x(k,b),p=e+gvjs_2x(k,b);m.move(n,
p);m.Ef(d,e,b,b,k+90,l+90,!0);n=d+gvjs_1x(l,f);p=e+gvjs_2x(l,f);m.va(n,p);m.Ef(d,e,f,f,l+90,k+90,!1);m.close();a.Ga(m,new gvjs_2({fill:h.color}),c)}if(this.yL||this.u4)this.yL&&(f=e-Math.round(.35*b),a.xi(this.yL,0,f,this.da,f,gvjs__,gvjs__,this.xL,c)),this.u4&&(f=e+Math.round(.35*b),a.xi(this.u4,0,f,this.da,f,gvjs__,gvjs__,this.xL,c));h=this.SD;k=.8*b;l=.9*b;n=this.Oba*h;p=(this.Cb-this.Ya)/n;var q=new gvjs_hy,r=new gvjs_hy,t=this.Mxa,u=Math.round(.14*b);t.fontSize=u;for(g=0;g<=n;g++){var v=gvjs_qS(this,
gvjs_lS(this,g*p+this.Ya)),w=0==g%h,x=w?k:l;m=w?q:r;var y=d+gvjs_1x(v,x);f=e+gvjs_2x(v,x);m.move(y,f);y=d+gvjs_1x(v,b);f=e+gvjs_2x(v,b);m.va(y,f);w&&this.Kz&&(m=this.Kz[Math.floor(g/h)])&&(y=d+gvjs_1x(v,x-u/2),f=e+gvjs_2x(v,x-u/2),x=gvjs__,280<v||90>v?(x=gvjs_T,v=0):90<=v&&260>v?(x=gvjs_1,v=y,y=this.da):(w=Math.min(y,this.da-y),v=y-w,y+=w,f+=Math.round(u/4)),a.xi(m,v,f,y,f,x,gvjs__,t,c))}a.Ga(r,gvjs_cja,c);a.Ga(q,gvjs_dja,c);this.qu();this.Jca=b;gvjs_mS(this);this.jva()};
gvjs_.Wta=function(a){this.OJ=a.x;gvjs_mS(this)};gvjs_.Vta=function(){this.qu()};gvjs_.qu=function(){this.cg&&(gvjs_fm(this.cg),this.cg.stop(!1),gvjs_J(this.cg),this.cg=null)};function gvjs_lS(a,b){a=(b-a.Ya)/(a.Cb-a.Ya);a=Math.max(a,-.02);return a=Math.min(a,1.02)}function gvjs_qS(a,b){return a.m6*b+gvjs_Zx((360-a.m6)/2+90)}
function gvjs_mS(a){if(a.C){var b=a.Jca,c=a.C,d=a.da/2,e=a.Pa/2,f=gvjs_qS(a,a.OJ),g=Math.round(.95*b),h=Math.round(.3*b),k=gvjs_1x(f,g);g=gvjs_2x(f,g);var l=gvjs_1x(f,h);h=gvjs_2x(f,h);f=gvjs_Zx(f+90);var m=.07*b,n=gvjs_1x(f,m);m=gvjs_2x(f,m);f=new gvjs_hy;f.move(d+k,e+g);f.mo(d+n,e+m,d-l+n/2,e-h+m/2,d-l,e-h);f.mo(d-l-n/2,e-h-m/2,d-n,e-m,d+k,e+g);k=Math.round(.15*b);(g=a.Ica)?c.Ac(g):g=a.Ica=c.Sa();a.nY&&(b=e+Math.round(.75*b),c.xi(a.nY,0,b,a.da,b,gvjs__,gvjs__,a.Mya,g));c.Ga(f,gvjs_eja,g);c.ze(d-
.5,e-.5,k,gvjs_fja,g);c.appendChild(a.xg,g)}}var gvjs_oS=new gvjs_2({fill:gvjs_Or,stroke:gvjs_Cr,strokeWidth:1}),gvjs_pS=new gvjs_2({fill:"#f7f7f7",stroke:gvjs_Pr,strokeWidth:2}),gvjs_cja=new gvjs_2({stroke:gvjs_Er,strokeWidth:1}),gvjs_dja=new gvjs_2({stroke:gvjs_Cr,strokeWidth:2}),gvjs_eja=new gvjs_2({fill:"#dc3912",fillOpacity:.7,stroke:"#c63310",strokeWidth:1}),gvjs_fja=new gvjs_2({fill:"#4684ee",stroke:gvjs_Er,strokeWidth:1});gvjs_=gvjs_kS.prototype;gvjs_.Ya=NaN;gvjs_.Cb=NaN;gvjs_.Oba=NaN;
gvjs_.SD=NaN;gvjs_.ce=0;gvjs_.nY=null;gvjs_.yL=null;gvjs_.u4=null;gvjs_.m6=270;gvjs_.Jca=0;gvjs_.Ica=null;gvjs_.OJ=null;gvjs_.Kz=null;gvjs_.cg=null;function gvjs_rS(a,b,c,d){this.ia=a;this.da=b;this.Pa=c;this.HO=d;this.Oy=[];this.uc=[];this.Kz=[];this.oY=[];this.Tq=[];this.Ya=0;this.Cb=100;this.n6=this.W1=this.cS=this.bS=this.t5=this.HU=this.GU=this.eZ=this.nP=this.mP=null;this.Fr=!0;this.U0=0}gvjs_=gvjs_rS.prototype;gvjs_.Mw=function(a){this.Ya!=a&&(this.Ya=a,this.Fr=!0)};gvjs_.yf=function(){return this.Ya};gvjs_.iu=function(a){this.Cb!=a&&(this.Cb=a,this.Fr=!0)};gvjs_.xf=function(){return this.Cb};gvjs_.setAnimation=function(a){this.n6=a};
gvjs_.setValues=function(a,b,c){this.Fr=this.Fr||this.uc.length!=a.length||this.Tq.length!=c.length||!gvjs_Cz(this.Tq,c);this.uc=a;this.oY=b;this.Tq=c};gvjs_.W2=function(a){1==a.length&&(a=["",a[0],""]);gvjs_Cz(this.Kz,a)||(this.Kz=a,this.Fr=!0)};function gvjs_sS(a,b,c){return Math.min(Math.floor(a.da/c),Math.floor(a.Pa/b))}gvjs_.draw=function(a){if(this.Fr)gvjs_gja(this,a);else for(a=0;a<this.uc.length;a++){var b=this.Oy[a];b.yL=this.Tq[a];b.Wa(this.uc[a],this.oY[a],this.n6)}};
function gvjs_gja(a,b){a.clear();var c=a.uc.length,d=1,e=1;if(1<c){var f=Math.floor(Math.sqrt(a.da*a.Pa/c));e=Math.floor(a.da/f);for(d=Math.floor(a.Pa/f);!(c<=Math.floor(a.da/f)*Math.floor(a.Pa/f));){var g=gvjs_sS(a,d,e+1),h=gvjs_sS(a,d+1,e);g>=h&&(f=g,e++);h>=g&&(f=h,d++)}}f=gvjs_sS(a,d,e);f-=0;h=gvjs_rl();h.Ac(a.ia);a.Oy=[];if(0!=c){var k=h.K(gvjs_ys,{style:gvjs_jS,cellpadding:0,cellspacing:0,align:gvjs__}),l=h.K(gvjs_zs,null);h.appendChild(k,l);g=[];for(var m=0,n=0;n<d;n++){var p=h.K(gvjs_Bs,{style:gvjs_jS});
h.appendChild(l,p);for(var q=0;q<e;q++){var r=h.K(gvjs_As,{style:"border: 0; padding: 0; margin: 0; width: "+f+"px;"});g[m++]=r;h.appendChild(p,r)}}h.appendChild(a.ia,k);d=Math.round(.1*f);a.U0=0;a.Fr=!0;for(e=0;e<c;e++)h=a.Oy[e]=new gvjs_kS(g[e],f,f,d,gvjs_q(function(){this.U0++;this.U0==this.Oy.length&&(this.Fr=!1)},a)),h.Mw(a.Ya),h.iu(a.Cb),h.yL=a.Tq[e],k=a.Kz,l=k.length,h.UE(1<l?l-1:4,a.SD),0<l&&h.W2(k),h.Wa(a.uc[e],a.oY[e],null),null!=a.mP&&null!=a.nP&&gvjs_nS(h,a.mP,a.nP,a.eZ),null!=a.GU&&null!=
a.HU&&gvjs_nS(h,a.GU,a.HU,a.t5),null!=a.bS&&null!=a.cS&&gvjs_nS(h,a.bS,a.cS,a.W1),h.draw(b,a.HO)}}gvjs_.clear=function(){for(var a=0;a<this.Oy.length;++a)this.Oy[a].clear();this.Oy=[]};gvjs_.SD=2;function gvjs_tS(a){gvjs_O.call(this,a);this.G=gvjs_rl()}gvjs_m(gvjs_tS,gvjs_O);gvjs_=gvjs_tS.prototype;
gvjs_.hg=function(a,b,c){var d=new gvjs_ji([c||{}]);c=this.container;var e=this.Oa(d),f=this.getHeight(d),g=gvjs_E(d,gvjs_Ju);if(e!=this.da||f!=this.Pa||g!=this.HO)this.fL&&this.fL.clear(),this.fL=new gvjs_rS(c,e,f,g),this.da=e,this.Pa=f,this.HO=g;c=this.fL;e=gvjs_F(d,gvjs_Nv,0);c.Mw(e);e=gvjs_F(d,gvjs_Fv,100);c.iu(e);e=d.ea("majorTicks",[String(c.yf()),"","","",String(c.xf())]);c.W2(e);e=gvjs_F(d,"minorTicks",2);c.SD!=e&&(c.SD=e,c.Fr=!0);e=d.Da("greenFrom");f=d.Da("greenTo");g=d.Da("yellowFrom");
var h=d.Da("yellowTo"),k=d.Da("redFrom"),l=d.Da("redTo"),m=gvjs_Jy(d,"greenColor",gvjs_Ar),n=gvjs_Jy(d,"yellowColor",gvjs_Lr),p=gvjs_Jy(d,"redColor",gvjs_Kr);if(c.mP!=e||c.nP!=f||c.eZ!=m||c.GU!=g||c.HU!=h||c.t5!=n||c.bS!=k||c.cS!=l||c.W1!=p)c.mP=e,c.nP=f,c.eZ=m,c.GU=g,c.HU=h,c.t5=n,c.bS=k,c.cS=l,c.W1=p,c.Fr=!0;d=gvjs_hK(d,400,gvjs_ev);c.setAnimation(d);d=[];e=[];f=[];if(2==b.Z()&&b.Y(0)==gvjs_j&&b.Y(1)==gvjs_f)for(g=0;g<b.ca();g++)null!=b.getValue(g,0)&&null!=b.getValue(g,1)&&(f.push(b.getValue(g,
0)),d.push(b.getValue(g,1)),e.push(b.Ha(g,1)));else for(h=0;h<b.Z();h++)if(b.Y(h)==gvjs_f)for(g=0;g<b.ca();g++)null!=b.getValue(g,h)&&(d.push(b.getValue(g,h)),e.push(b.Ha(g,h)),f.push(b.Ca(h)));c.setValues(d,e,f);c.draw(a);gvjs_N(this,gvjs_g,null)};gvjs_.nf=function(){this.fL&&this.fL.clear()};gvjs_.da=0;gvjs_.Pa=0;gvjs_.HO=!0;gvjs_o(gvjs_rc,gvjs_tS,void 0);gvjs_tS.prototype.draw=gvjs_tS.prototype.draw;gvjs_tS.prototype.clearChart=gvjs_tS.prototype.Lb;gvjs_tS.prototype.getContainer=gvjs_tS.prototype.getContainer;
