var gvjs_Ho=" 0 0 1 ",gvjs_Io=' xmlns:svg="http://www.w3.org/2000/svg"',gvjs_Jo=' xmlns:xlink="http://www.w3.org/1999/xlink">',gvjs_Ko="0 0",gvjs_Lo="0%",gvjs_Mo="100%",gvjs_No='<?xml version="1.0"?>',gvjs_Oo='<body marginwidth="0" marginheight="0"',gvjs_Po="<head>",gvjs_Qo='<html xmlns:v="urn:schemas-microsoft-com:vml">',gvjs_Ro='<html xmlns="http://www.w3.org/1999/xhtml"',gvjs_So='<script type="text/javascript">',gvjs_To="<style> v\\:* { behavior:url(#default#VML);}</style>",gvjs_Uo="Arial",gvjs_Vo=
"BUTTON",gvjs_Wo="Drawing_Frame_",gvjs_Xo="SELECT",gvjs_Yo="TEXTAREA",gvjs_R="absolute",gvjs_Zo="aria-hidden",gvjs__o="baseline",gvjs_0o="black",gvjs_1o="blur",gvjs_2o="bold",gvjs_3o="circle",gvjs_4o="clip-path",gvjs_S="color",gvjs_5o="corners.bottomleft.rx",gvjs_6o="corners.bottomleft.ry",gvjs_7o="corners.bottomright.rx",gvjs_8o="corners.bottomright.ry",gvjs_9o="corners.rx",gvjs_$o="corners.ry",gvjs_ap="corners.topleft.rx",gvjs_bp="corners.topleft.ry",gvjs_cp="corners.topright.rx",gvjs_dp="corners.topright.ry",
gvjs_ep="datatable",gvjs_fp="datum",gvjs_gp="defs",gvjs_hp="ellipse",gvjs_T="end",gvjs_ip="feComponentTransfer",gvjs_jp="feGaussianBlur",gvjs_kp="feMergeNode",gvjs_lp="fill",gvjs_mp="fill-opacity",gvjs_np="fill.color",gvjs_op="fill.opacity",gvjs_pp="fillColor",gvjs_qp="fillOpacity",gvjs_rp="filter",gvjs_sp="finishAnimation",gvjs_tp="font.family",gvjs_up="font.size",gvjs_vp="fontFamily",gvjs_wp="fontName",gvjs_xp="fontSize",gvjs_yp="getcontext",gvjs_zp="gradient",gvjs_Ap="group",gvjs_Bp="halign",gvjs_Cp=
"hidden",gvjs_Dp="highlight",gvjs_Ep="http://www.w3.org/2000/svg",gvjs_Fp="in",gvjs_Gp="italic",gvjs_Hp="linear",gvjs_Ip="linearGradient",gvjs_Jp="ltr",gvjs_Kp="nowrap",gvjs_Lp="offset",gvjs_Mp="opacity",gvjs_Np="path",gvjs_Op="playAnimation",gvjs_U="px",gvjs_Pp="rabl-use-parent",gvjs_Qp="rect",gvjs_Rp="redraw",gvjs_Sp="rotate",gvjs_Tp="rotate(",gvjs_Up="rtl",gvjs_Vp="shadow.opacity",gvjs_Wp="shadow.radius",gvjs_Xp="shadow.xoffset",gvjs_Yp="shadow.yoffset",gvjs_Zp="single",gvjs__p="slice",gvjs_0p=
"stop",gvjs_1p="stroke",gvjs_2p="stroke-opacity",gvjs_3p="stroke-width",gvjs_4p="stroke.color",gvjs_5p="stroke.opacity",gvjs_6p="stroke.width",gvjs_7p="strokeColor",gvjs_8p="strokeOpacity",gvjs_9p="strokeWidth",gvjs_$p="svg",gvjs_aq="text-anchor",gvjs_bq="transform",gvjs_cq="underline",gvjs_dq='unknown property on ellipse "',gvjs_eq="url(#",gvjs_fq="valign",gvjs_gq="var _loaded = false;",gvjs_V="vertical";function gvjs_W(a,b){return gvjs_4d[a]=b}
gvjs_A.prototype.Oa=gvjs_W(11,function(){return this.right-this.left});gvjs_O.prototype.Oa=gvjs_W(10,function(a,b){return a.bD(gvjs_Zd)||gvjs_Hk(this.container).width||b||400});function gvjs_hq(a,b,c){gvjs_Se(a,c,0,b)}function gvjs_iq(a){return a?a.parentWindow||a.defaultView:window}function gvjs_jq(a,b,c){b=gvjs_jaa(b,function(d,e){var f={};return f[e]=d,f},c);gvjs_bi(a,b)}
function gvjs_kq(a,b,c){if(a.TM){var d={};gvjs_jq(d,a.TM[0].split("."),c);c=d}for(var e=d=0;e<b;e++)e===a.sJ.length&&a.sJ.push(0),d+=a.sJ[e];a.sJ[b]++;gvjs_hq(a.He,c,d)}function gvjs_lq(a,b,c){return gvjs_oi(a,gvjs_ui,0,b,c)}function gvjs_mq(a,b){b=gvjs_ve(gvjs_J,b);a.Rg?b():(a.Xz||(a.Xz=[]),a.Xz.push(b))}function gvjs_nq(a){if(!(a instanceof Array)){a=gvjs_$d(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
function gvjs_oq(a){if(!Array.isArray(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0}function gvjs_pq(a){var b=arguments.length;if(1==b&&Array.isArray(arguments[0]))return gvjs_pq.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c}
var gvjs_eda=/<[^>]*>|&[^;]+;/g,gvjs_fda=/[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0900-\u1fff\u200e\u2c00-\ud801\ud804-\ud839\ud83c-\udbff\uf900-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]/,gvjs_gda=/^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0900-\u1fff\u200e\u2c00-\ud801\ud804-\ud839\ud83c-\udbff\uf900-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u06ef\u06fa-\u08ff\u200f\ud802-\ud803\ud83a-\ud83b\ufb1d-\ufdff\ufe70-\ufefc]/,gvjs_hda=/^http:\/\/.*/,gvjs_ida=/\s+/,gvjs_jda=
/[\d\u06f0-\u06f9]/;function gvjs_qq(a,b){var c=0,d=0,e=!1;a=(b?a.replace(gvjs_eda,""):a).split(gvjs_ida);for(b=0;b<a.length;b++){var f=a[b];gvjs_gda.test(f)?(c++,d++):gvjs_hda.test(f)?e=!0:gvjs_fda.test(f)?d++:gvjs_jda.test(f)&&(e=!0)}return 0==d?e?1:0:.4<c/d?-1:1}function gvjs_rq(a,b){return a==b?!0:a&&b?a.width==b.width&&a.height==b.height:!1}function gvjs_sq(a,b){a&&(a.logicalname=b)}function gvjs_tq(a,b){this.key=a;this.value=b}
gvjs_tq.prototype.remove=function(){this.Vi.next=this.next;this.next.Vi=this.Vi;delete this.Vi;delete this.next};function gvjs_uq(a,b){this.Zba=a||null;this.Dd=!!b;this.s9=void 0;this.ta=new gvjs__h;this.zc=new gvjs_tq("",void 0);this.zc.next=this.zc.Vi=this.zc}function gvjs_vq(a,b){(b=a.ta.get(b))&&a.Dd&&(b.remove(),gvjs_wq(a,b));return b}gvjs_=gvjs_uq.prototype;gvjs_.get=function(a,b){return(a=gvjs_vq(this,a))?a.value:b};
gvjs_.set=function(a,b){var c=gvjs_vq(this,a);c?c.value=b:(c=new gvjs_tq(a,b),this.ta.set(a,c),gvjs_wq(this,c))};gvjs_.peek=function(){return this.zc.next.value};gvjs_.shift=function(){return gvjs_xq(this,this.zc.next)};gvjs_.pop=function(){return gvjs_xq(this,this.zc.Vi)};gvjs_.remove=function(a){return(a=this.ta.get(a))?(this.removeNode(a),!0):!1};gvjs_.removeNode=function(a){a.remove();this.ta.remove(a.key)};gvjs_.tb=function(){return this.ta.tb()};gvjs_.isEmpty=function(){return this.ta.isEmpty()};
gvjs_.kj=function(){return this.map(function(a,b){return b})};gvjs_.La=function(){return this.map(function(a){return a})};gvjs_.contains=function(a){return this.some(function(b){return b==a})};gvjs_.Pe=function(a){return this.ta.Pe(a)};gvjs_.clear=function(){gvjs_yq(this,0)};gvjs_.forEach=function(a,b){for(var c=this.zc.next;c!=this.zc;c=c.next)a.call(b,c.value,c.key,this)};gvjs_.map=function(a,b){for(var c=[],d=this.zc.next;d!=this.zc;d=d.next)c.push(a.call(b,d.value,d.key,this));return c};
gvjs_.some=function(a,b){for(var c=this.zc.next;c!=this.zc;c=c.next)if(a.call(b,c.value,c.key,this))return!0;return!1};gvjs_.every=function(a,b){for(var c=this.zc.next;c!=this.zc;c=c.next)if(!a.call(b,c.value,c.key,this))return!1;return!0};function gvjs_wq(a,b){a.Dd?(b.next=a.zc.next,b.Vi=a.zc,a.zc.next=b,b.next.Vi=b):(b.Vi=a.zc.Vi,b.next=a.zc,a.zc.Vi=b,b.Vi.next=b);null!=a.Zba&&gvjs_yq(a,a.Zba)}
function gvjs_yq(a,b){for(;a.tb()>b;){var c=a.Dd?a.zc.Vi:a.zc.next;a.removeNode(c);a.s9&&a.s9(c.key,c.value)}}function gvjs_xq(a,b){a.zc!=b&&a.removeNode(b);return b.value}function gvjs_zq(a){this.$ka=Math.max(1,a||Infinity);this.Dd=new gvjs_uq(this.$ka,!0)}gvjs_=gvjs_zq.prototype;gvjs_.clear=function(){this.Dd.clear()};gvjs_.contains=function(a){return this.Dd.Pe(a)};gvjs_.get=function(a){if(!this.contains(a))throw Error('Cache does not contain key "'+a+'"');return this.Dd.get(a)};
gvjs_.put=function(a,b){this.Dd.set(a,b);return b};gvjs_.size=function(){return this.Dd.tb()};function gvjs_kda(a,b){a=[a];for(var c=b.length-1;0<=c;--c)a.push(typeof b[c],b[c]);return a.join("\x0B")}function gvjs_Aq(a,b){function c(){var h=f(gvjs_te(d),arguments);return g.contains(h)?g.get(h):g.put(h,d.apply(this,arguments))}var d=null,e={};typeof a===gvjs_c?(d=a,e=b||{}):typeof b===gvjs_c&&(d=b,e=a||{});var f=e.QS||gvjs_kda,g=e.cache||new gvjs_zq(1E3);c.clear=function(){g.clear()};return c}
function gvjs_Bq(a,b){typeof a==gvjs_f&&(a=(b?Math.round(a):a)+gvjs_U);return a}function gvjs_Cq(a,b,c){if(b instanceof gvjs_u){var d=b.x;b=b.y}else d=b,b=c;a.style.left=gvjs_Bq(d,!1);a.style.top=gvjs_Bq(b,!1)}function gvjs_Dq(a,b){a.style.width=gvjs_Bq(b,!0)}function gvjs_Eq(a,b,c){if(b instanceof gvjs_y)c=b.height,b=b.width;else if(void 0==c)throw Error("missing height argument");gvjs_Dq(a,b);a.style.height=gvjs_Bq(c,!0)}
function gvjs_Fq(a){var b=null,c=null;typeof a===gvjs_c?b=a:c=a;this.Rla=b;this.H=c;this.DQ=null}gvjs_Fq.prototype.Cm=gvjs_l(23);gvjs_Fq.prototype.Fq=gvjs_l(25);gvjs_Fq.prototype.j=function(){this.H||(this.H=this.Rla(),null!==this.DQ&&gvjs_sq(this.H,this.DQ));return this.H};function gvjs_Gq(a,b){gvjs_I.call(this);this.container=a;this.oF=b;this.jw=null;this.hf=gvjs_Aq(gvjs_q(function(c,d,e){return this.KC(c,d,e)},this),{QS:function(c,d){var e=[c,d[0]];gvjs_v(d[1],function(f,g){e.push(f);e.push(g)});e.push(+d[2]);return"getTextSize_"+e.join("_")}});this.Iw=null}gvjs_r(gvjs_Gq,gvjs_I);
function gvjs_Hq(){var a=gvjs_rl().ek();a.__googleVisualizationAbstractRendererElementsCount__=a.__googleVisualizationAbstractRendererElementsCount__||0;var b="_ABSTRACT_RENDERER_ID_"+a.__googleVisualizationAbstractRendererElementsCount__.toString();a.__googleVisualizationAbstractRendererElementsCount__++;return b}gvjs_=gvjs_Gq.prototype;gvjs_.width=0;gvjs_.height=0;gvjs_.Ql=gvjs_l(29);gvjs_.deleteContents=function(){this.vX()};gvjs_.flush=function(){};gvjs_.clear=function(){this.nf()};
gvjs_.nf=function(){this.jw=null};gvjs_.O=function(){this.nf();gvjs_Gq.o.O.call(this)};gvjs_.getContainer=function(){return this.container};gvjs_.Cm=gvjs_l(22);gvjs_.Fq=gvjs_l(24);gvjs_.appendChild=function(a,b){if(b){if(b.constructor==gvjs_Fq){if(!b.H)return;b=b.j()}a.j().appendChild(b)}};function gvjs_Iq(a,b){b instanceof gvjs_Fq&&(b=b.j());for(var c;c=b.firstChild;)gvjs_Iq(a,c);b.parentElement.removeChild(b)}
gvjs_.replaceChild=function(a,b,c){a=a.j();gvjs_Dh(c)!=a?(gvjs_Iq(this,c),a.appendChild(b)):a.replaceChild(b,c)};gvjs_.Ac=function(a){if(a.H){var b=a.j();this.gv.Ac(b);a.j()}};gvjs_.Sa=gvjs_l(32);gvjs_.oy=gvjs_l(35);gvjs_.fC=gvjs_l(36);gvjs_.Dc=gvjs_l(37);gvjs_.ze=gvjs_l(50);gvjs_.Yk=gvjs_l(53);gvjs_.rb=gvjs_l(56);gvjs_.kO=gvjs_l(59);gvjs_.Ga=gvjs_l(60);gvjs_.Ud=gvjs_l(61);gvjs_.xi=gvjs_l(64);gvjs_.il=gvjs_l(67);gvjs_.bw=gvjs_l(69);gvjs_.YB=gvjs_Ze;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function gvjs_Jq(a){gvjs_I.call(this);this.vd=a;this.fd={}}gvjs_r(gvjs_Jq,gvjs_I);var gvjs_Kq=[];gvjs_=gvjs_Jq.prototype;gvjs_.D=function(a,b,c,d){return gvjs_Lq(this,a,b,c,d)};function gvjs_Lq(a,b,c,d,e,f){Array.isArray(c)||(c&&(gvjs_Kq[0]=c.toString()),c=gvjs_Kq);for(var g=0;g<c.length;g++){var h=gvjs_K(b,c[g],d||a.handleEvent,e||!1,f||a.vd||a);if(!h)break;a.fd[h.key]=h}return a}gvjs_.yD=function(a,b,c,d){return gvjs_Mq(this,a,b,c,d)};
function gvjs_Mq(a,b,c,d,e,f){if(Array.isArray(c))for(var g=0;g<c.length;g++)gvjs_Mq(a,b,c[g],d,e,f);else{b=gvjs_9l(b,c,d||a.handleEvent,e,f||a.vd||a);if(!b)return a;a.fd[b.key]=b}return a}gvjs_.Ab=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)this.Ab(a,b[f],c,d,e);else c=c||this.handleEvent,d=gvjs_p(d)?!!d.capture:!!d,e=e||this.vd||this,c=gvjs_$l(c),d=!!d,b=gvjs_1l(a)?a.lI(b,c,d,e):a?(a=gvjs_bm(a))?a.lI(b,c,d,e):null:null,b&&(gvjs_em(b),delete this.fd[b.key]);return this};
gvjs_.removeAll=function(){gvjs_v(this.fd,function(a,b){this.fd.hasOwnProperty(b)&&gvjs_em(a)},this);this.fd={}};gvjs_.O=function(){gvjs_Jq.o.O.call(this);this.removeAll()};gvjs_.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var gvjs_lda=function(){if(gvjs_2g){var a=/Windows NT ([0-9.]+)/;return(a=a.exec(gvjs_gg))?a[1]:"0"}return gvjs_1g?(a=/10[_.][0-9_.]+/,(a=a.exec(gvjs_gg))?a[0].replace(/_/g,"."):"10"):gvjs_Maa?(a=/Android\s+([^\);]+)(\)|;)/,(a=a.exec(gvjs_gg))?a[1]:""):gvjs_Naa||gvjs_Oaa||gvjs_Paa?(a=/(?:iPhone|CPU)\s+OS\s+(\S+)/,(a=a.exec(gvjs_gg))?a[1].replace(/_/g,"."):""):""}();function gvjs_Nq(a){return(a=a.exec(gvjs_gg))?a[1]:""}
var gvjs_mda=function(){if(gvjs_Aba)return gvjs_Nq(/Firefox\/([0-9.]+)/);if(gvjs_x||gvjs_Zg||gvjs_Yg)return gvjs_$g;if(gvjs_Cba)return gvjs_Vg()?gvjs_Nq(/CriOS\/([0-9.]+)/):gvjs_Nq(/Chrome\/([0-9.]+)/);if(gvjs_Qk&&!gvjs_Vg())return gvjs_Nq(/Version\/([0-9.]+)/);if(gvjs_Ok||gvjs_Pk){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(gvjs_gg);if(a)return a[1]+"."+a[2]}else if(gvjs_Bba)return(a=gvjs_Nq(/Android\s+([0-9.]+)/))?a:gvjs_Nq(/Version\/([0-9.]+)/);return""}();function gvjs_Oq(a,b){gvjs_Gq.call(this,a,b);this.gv=gvjs_fh(a);this.eO=this.gv.pc();this.vu=[];this.aa=new gvjs_Jq}gvjs_r(gvjs_Oq,gvjs_Gq);gvjs_=gvjs_Oq.prototype;gvjs_.Ie=gvjs_l(71);gvjs_.clear=function(){this.aa.removeAll();gvjs_J(this.aa);this.aa=new gvjs_Jq;gvjs_Oq.o.clear.call(this)};gvjs_.nf=function(){gvjs_Oq.o.nf.call(this);gvjs_s(this.vu,function(a){gvjs_J(a)});gvjs_oq(this.vu);this.gv.Ac(this.container);this.aa.removeAll();gvjs_J(this.aa)};gvjs_.el=gvjs_l(74);gvjs_.ec=gvjs_l(76);
gvjs_.replaceChild=function(a,b,c){gvjs_Oq.o.replaceChild.call(this,a,b,c);gvjs_fm(c)};function gvjs_Pq(a){gvjs_I.call(this);this.ia=a;this.aa=new gvjs_Jq}gvjs_r(gvjs_Pq,gvjs_I);gvjs_=gvjs_Pq.prototype;gvjs_.getContainer=function(){return this.ia};gvjs_.clear=function(){this.WG();this.aa=new gvjs_Jq};gvjs_.WG=function(){gvjs_uh(this.ia);this.aa.removeAll();gvjs_J(this.aa)};gvjs_.O=function(){this.WG();gvjs_Pq.o.O.call(this)};gvjs_.ec=gvjs_l(75);function gvjs_Qq(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("[goog.string.format] Template required");return d.replace(/%([0\- \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(e,f,g,h,k,l,m,n){if("%"==l)return"%";var p=c.shift();if("undefined"==typeof p)throw Error("[goog.string.format] Not enough arguments");arguments[0]=p;return gvjs_Rq[l].apply(null,arguments)})}
var gvjs_Rq={s:function(a,b,c){return isNaN(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+gvjs_Gg(" ",Number(c)-a.length):gvjs_Gg(" ",Number(c)-a.length)+a},f:function(a,b,c,d,e){d=a.toString();isNaN(e)||""==e||(d=parseFloat(a).toFixed(e));var f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if(isNaN(c)||d.length>=Number(c))return d;d=isNaN(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;0<=b.indexOf("-",
0)?d=f+d+gvjs_Gg(" ",a):(b=0<=b.indexOf("0",0)?"0":" ",d=f+gvjs_Gg(b,a)+d);return d},d:function(a,b,c,d,e,f,g,h){return gvjs_Rq.f(parseInt(a,10),b,c,d,0,f,g,h)}};gvjs_Rq.i=gvjs_Rq.d;gvjs_Rq.u=gvjs_Rq.d;function gvjs_Sq(a,b){gvjs_Oq.call(this,a,b);this.nq=null;this.KR={};this.cZ={};this.f3={};this.KC("-._.-*^*-._.-*^*-._.-",{fontSize:8,hb:gvjs_Uo,bold:!1,ed:!1});this.eQ=!1;for(a=this.container.parentElement.parentElement;a;){if(null!=a.getAttribute("dir")){this.eQ=a.getAttribute("dir")===gvjs_Up;break}a=a.parentElement}}gvjs_r(gvjs_Sq,gvjs_Oq);function gvjs_Tq(a,b){a.nq=a.kb(gvjs_gp);var c=gvjs_Hq();a.nq.setAttribute(gvjs_9c,c);a.KR={};a.cZ={};a.f3={};b.appendChild(a.nq)}gvjs_=gvjs_Sq.prototype;
gvjs_.ZB=gvjs_l(31);gvjs_.el=gvjs_l(73);gvjs_.vX=function(){for(var a=this.jw.j(),b=a.childNodes,c=b.length;1<c;)a.removeChild(b[0]),c--;gvjs_Tq(this,a)};gvjs_.h$=gvjs_l(77);gvjs_.round=function(a){return Math.round(100*a)/100};gvjs_.Fs=gvjs_l(52);gvjs_.kH=gvjs_l(55);gvjs_.Uj=gvjs_l(58);gvjs_.ED=gvjs_l(82);gvjs_.nH=gvjs_l(49);gvjs_.Hs=gvjs_l(63);gvjs_.ey=gvjs_l(66);gvjs_.Co=gvjs_l(84);gvjs_.by=gvjs_l(88);gvjs_.wy=gvjs_l(86);gvjs_.lH=gvjs_l(34);gvjs_.Tx=gvjs_l(90);gvjs_.Vc=gvjs_l(39);gvjs_.Ka=gvjs_l(41);
gvjs_.no=gvjs_l(43);gvjs_.Nh=gvjs_l(47);gvjs_.Kk=gvjs_l(45);gvjs_.Dm=gvjs_l(92);gvjs_.rg=gvjs_l(94);gvjs_.Bj=gvjs_l(96);gvjs_.vA=gvjs_l(99);gvjs_.zA=gvjs_l(102);gvjs_.gd=gvjs_l(151);
gvjs_.KC=function(a,b,c){var d=this.oF;if(3===d.firstChild.nodeType)d.firstChild.data=a;else throw Error("Unexpected type of text node "+d.firstChild.nodeType);a=d.style;a.fontFamily=b.hb;a.fontSize=b.fontSize+gvjs_U;a.fontWeight=b.bold?gvjs_2o:"";a.fontStyle=b.ed?gvjs_Gp:"";a.display=gvjs_Bb;null!=c&&(b=gvjs_Qq("rotate(%ddeg)",c),a.transform=b,a.transformOrigin=gvjs_Ko,a.WebkitTransform=b,a.WebkitTransformOrigin=gvjs_Ko,a.MozTransform=b,a.MozTransformOrigin=gvjs_Ko,a.MAa=b,a.NAa=gvjs_Ko,a.msTransform=
b,a.$Ca=gvjs_Ko);b=d.clientWidth;d=d.clientHeight;a.display=gvjs_e;return new gvjs_y(b,d)};gvjs_.IC=gvjs_l(105);gvjs_.kb=function(a){return this.eO.createElementNS(gvjs_Ep,a)};gvjs_.ji=gvjs_l(79);gvjs_.YB=gvjs_l(70);function gvjs_Uq(a,b){gvjs_Oq.call(this,a,b);this.Vw=null}gvjs_r(gvjs_Uq,gvjs_Oq);gvjs_=gvjs_Uq.prototype;gvjs_.ZB=gvjs_l(30);gvjs_.vX=function(){for(var a=this.jw.j(),b=a.childNodes,c=b.length;1<c;)a.removeChild(b[0]),c--};gvjs_.round=function(a){return Math.round(a)};gvjs_.Fs=gvjs_l(51);gvjs_.kH=gvjs_l(54);gvjs_.Uj=gvjs_l(57);gvjs_.ED=gvjs_l(81);gvjs_.nH=gvjs_l(48);gvjs_.Hs=gvjs_l(62);gvjs_.ey=gvjs_l(65);gvjs_.Co=gvjs_l(83);gvjs_.by=gvjs_l(87);gvjs_.wy=gvjs_l(85);gvjs_.lH=gvjs_l(33);gvjs_.Tx=gvjs_l(89);
gvjs_.Vc=gvjs_l(38);gvjs_.Ka=gvjs_l(40);gvjs_.no=gvjs_l(42);gvjs_.Nh=gvjs_l(46);gvjs_.Kk=gvjs_l(44);gvjs_.Dm=gvjs_l(91);gvjs_.rg=gvjs_l(93);gvjs_.Bj=gvjs_l(95);gvjs_.vA=gvjs_l(98);gvjs_.zA=gvjs_l(101);gvjs_.gd=gvjs_l(150);
gvjs_.KC=function(a,b){var c=this.oF;c.firstChild.data=a;a=c.style;a.fontFamily=b.hb;a.fontSize=this.Yb(b.fontSize||0);a.fontWeight=b.bold?gvjs_2o:"";a.fontStyle=b.ed?gvjs_Gp:"";a.display=gvjs_Bb;var d=c.clientWidth;c=c.clientHeight;a.display=gvjs_e;b.bold&&(d*=1.1);b.ed&&(d*=.9);return new gvjs_y(d,c)};gvjs_.IC=gvjs_l(104);gvjs_.Yb=function(a){return Math.round(a)+gvjs_U};gvjs_.Td=function(a){return this.eO.createElement(a)};gvjs_.ji=gvjs_l(78);gvjs_.Cj=gvjs_l(106);gvjs_.bw=gvjs_l(68);var gvjs_Vq;gvjs_pq(["A","AREA",gvjs_Vo,"HEAD",gvjs_Qa,"LINK","MENU","META","OPTGROUP","OPTION","PROGRESS",gvjs_ab,gvjs_Xo,gvjs_9a,gvjs_Yo,"TITLE","TRACK"]);
function gvjs_Wq(a,b,c){Array.isArray(c)&&(c=c.join(" "));var d="aria-"+b;""===c||void 0==c?(gvjs_Vq||(gvjs_Vq={atomic:!1,autocomplete:gvjs_e,dropeffect:gvjs_e,haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:gvjs_V,readonly:!1,relevant:"additions text",required:!1,sort:gvjs_e,busy:!1,disabled:!1,hidden:!1,invalid:gvjs_Wb}),c=gvjs_Vq,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)};function gvjs_Xq(a,b,c,d){gvjs_I.call(this);if(!(gvjs_x?0<=gvjs_Tf(gvjs_$g,"5.5"):gvjs__g?0<=gvjs_Tf(gvjs_$g,"1.8"):gvjs_Yg?0<=gvjs_Tf(gvjs_$g,"9.0"):gvjs_0g?0<=gvjs_Tf(gvjs_$g,"420+"):gvjs_Zg))throw Error("Graphics is not supported");for(var e=Math.floor(1E5*Math.random());window.frames[gvjs_Wo+e];)e++;this.cl=gvjs_Wo+e;(a=this.SL=a)&&(a.referencepoint=!0);gvjs_uh(this.SL);this.Yj=gvjs_fh(this.SL);this.container=this.Yj.createElement(gvjs_Sb);this.container.style.position=gvjs_Dd;this.SL.appendChild(this.container);
this.Vk=b;this.i4=this.wm=null;this.vt=!1;this.zE=[];this.Ti=null;b=gvjs_sl();this.tva=(b=gvjs_x?null!=b.documentMode?9>b.documentMode:!gvjs_ah("9"):!1)?gvjs_Uq:gvjs_Sq;if(this.rU=b||d)d=this.Yj.K(gvjs_Pa),d.name=this.cl,d.id=this.cl,d.width=this.Vk.width.toString(),d.height=this.Vk.height.toString(),d.frameBorder="0",d.scrolling="no",d.marginHeight="0",d.marginWidth="0",d.allowTransparency=gvjs_Ud,b||(d.type="image/svg+xml"),this.Yj.appendChild(this.container,d),d=this.Yj.g$(d),d.open(),a=[],b?(a.push(gvjs_Qo),
a.push(gvjs_Po),a.push(gvjs_To)):(a.push(gvjs_No),a.push(gvjs_Ro),a.push(gvjs_Io),a.push(gvjs_Jo),a.push(gvjs_Po)),a.push(gvjs_So),a.push(gvjs_gq),a.push("function CHART_loaded() {"),a.push(" _loaded = true;"),a.push("}"),a.push("\x3c/script>"),a.push("</head>"),a.push(gvjs_Oo),a.push(' style="background:transparent"'),a.push(' onload="CHART_loaded()"'),a.push(">"),a.push('<div id="renderers"></div>'),a.push("</body>"),a.push("</html>"),d.write(a.join("\n")),d.close();gvjs_Yq(this,c)}
gvjs_r(gvjs_Xq,gvjs_I);function gvjs_Yq(a,b){var c=gvjs_q(a.Xra,a);a=gvjs_q(a.iua,a);gvjs_Zq(c,a,b)}gvjs_=gvjs_Xq.prototype;
gvjs_.iua=function(){if(this.rU){var a=(a=this.Yj.j(this.cl))?this.Yj.g$(a):null;var b=this.wm=a.getElementById("renderers");b&&(b.referencepoint=!0);this.i4=gvjs__q(a.body,this.Vk)}else this.wm=this.Yj.createElement(gvjs_Sb),gvjs_H(this.wm,gvjs_zd,gvjs_Dd),gvjs_Eq(this.wm,this.Vk),this.wm.dir=gvjs_Jp,this.container.appendChild(this.wm),this.i4=gvjs__q(this.container,this.Vk);this.vt=!0};
function gvjs__q(a,b){var c=gvjs_fh(a),d=c.createElement(gvjs_Sb),e=d.style;e.display=gvjs_e;e.position=gvjs_R;e.top=b.height+10+gvjs_U;e.left=b.width+10+gvjs_U;e.whiteSpace=gvjs_Kp;gvjs_Wq(d,gvjs_Cp,!0);d.setAttribute(gvjs_Zo,!0);c.appendChild(d,c.createTextNode(" "));c.appendChild(a,d);return d}
gvjs_.Xra=function(){if(!this.rU)return!0;var a=this.Yj.j(this.cl);if(a)a:{try{var b=a.contentWindow||(a.contentDocument?gvjs_iq(a.contentDocument):null);break a}catch(c){}b=null}else b=null;return(a=b)&&a._loaded};gvjs_.$a=function(a){if(!this.vt)return null;for(a=null!=a?a:0;this.zE.length<=a;){var b=gvjs_fh(this.wm).createElement(gvjs_Sb);gvjs_H(b,gvjs_zd,gvjs_R);gvjs_Cq(b,0,0);gvjs_Eq(b,gvjs_Mo,gvjs_Mo);this.wm.appendChild(b);b=new this.tva(b,this.i4);gvjs_mq(this,b);this.zE.push(b)}return this.zE[a]};
gvjs_.xv=function(){if(!this.vt)return null;if(!this.Ti){var a=this.Yj.createElement(gvjs_Sb);this.Ti=new gvjs_Pq(a);this.Yj.appendChild(this.container,this.Ti.getContainer())}return this.Ti};gvjs_.fo=function(a,b){gvjs_Zq(gvjs_q(function(){return null!=this.wm},this),a,b)};gvjs_.update=function(a,b){if(!gvjs_rq(this.Vk,a))if(this.Vk=a,this.rU){if(a=this.Yj.j(this.cl))a.width=this.Vk.width.toString(),a.height=this.Vk.height.toString()}else this.vt&&gvjs_Eq(this.wm,this.Vk);this.vt||gvjs_Yq(this,b)};
function gvjs_Zq(a,b,c,d){a.call()?b.call():gvjs_nda(a,b,c,d)}function gvjs_nda(a,b,c,d){var e=null!=d?d:10;window.setTimeout(c(function(){gvjs_Zq(a,b,c,e)}),e)}gvjs_.O=function(){try{this.Yj.Ac(this.SL),gvjs_J(this.Ti),gvjs_s(this.zE,function(a){gvjs_J(a)})}catch(a){}gvjs_Xq.o.O.call(this)};function gvjs_0q(){}gvjs_0q.prototype.D=function(a,b){gvjs_1q(this,a);this.XH[a].push(b);return this};gvjs_0q.prototype.Ab=function(a,b){gvjs_1q(this,a);a=this.XH[a];for(var c=null,d=0,e=a.length;d<e;d++)if(a[d]===b){c=d;break}return null!=c?(a.splice(c,1),!0):!1};gvjs_0q.prototype.fireEvent=function(a,b){gvjs_1q(this,a);a=this.XH[a];for(var c=[],d=0,e=a.length;d<e;d++)c.push(a[d]);for(d=0;d<e;d++)c[d].apply(this,b);return 0<e};
function gvjs_1q(a,b){if(!a.XH.hasOwnProperty(b))throw'event type "'+b+'" unknown.';};function gvjs_2q(a){this.XH={add:[],click:[],getcontext:[],mousemove:[],mouseenter:[],mouseleave:[],box:[],redraw:[],remove:[],playAnimation:[],finishAnimation:[]};this.Wb=this.qa=null;this.tc={};this.oo=[];this.OR=[];if(null!=a)for(var b in a)this.setStyle(b,a[b]);this.o5=null}gvjs_r(gvjs_2q,gvjs_0q);gvjs_=gvjs_2q.prototype;gvjs_.data=function(a){return void 0!==a?(this.qa=a,this):this.qa};gvjs_.setData=function(a){this.qa=a;return this};
gvjs_.setStyle=function(a,b){b instanceof Object&&null!=b&&(b=b.toString());if(this.tc[a]===b)return!1;this.tc[a]=b;this.uo=null;return!0};gvjs_.getStyle=function(a){return this.tc[a]};function gvjs_3q(a){null==a.o5&&(a.o5=new gvjs_ji([a.tc],void 0,!0));return a.o5}gvjs_.style=function(a,b){return void 0!==b?(this.setStyle(a,b)&&this.fireEvent(gvjs_Rp,[this,a]),this):this.getStyle(a)};gvjs_.styles=function(a){for(var b in a)a.hasOwnProperty(b)&&this.style(b,a[b]);return this};
gvjs_.getContext=function(){this.Wb||this.fireEvent(gvjs_yp,[this]);return this.Wb};gvjs_.el=gvjs_l(72);gvjs_.Ru=gvjs_l(108);gvjs_.fDa=function(){for(var a=this;0<this.oo.length;){var b=this.oo.shift();a.OR.push(b);b.D(gvjs_sp,function(c,d){c=a.OR.indexOf(d);if(0>c)throw"Animation not found.";a.OR.splice(c,1);0===a.OR.length&&a.fireEvent(gvjs_sp,[a])});if(!this.fireEvent(gvjs_Op,[this,b]))throw"Cannot play animations for shape not in a scene.";}return this};var gvjs_oda=gvjs_n.requestAnimationFrame||gvjs_n.mozRequestAnimationFrame||gvjs_n.webkitRequestAnimationFrame||gvjs_n.msRequestAnimationFrame||function(a){return gvjs_n.setTimeout(function(){return a.call(this,gvjs_we())},1E3/60)};function gvjs_4q(a){a%=360;return 0>360*a?a+360:a};function gvjs_5q(a){gvjs_2q.call(this,a);this.uo={x1:null,y1:null,x2:null,y2:null,width:0,height:0};this.av=[]}gvjs_m(gvjs_5q,gvjs_2q);gvjs_=gvjs_5q.prototype;gvjs_.gl=gvjs_l(113);gvjs_.Ru=gvjs_l(107);gvjs_.clear=function(){this.uo={x1:null,y1:null,x2:null,y2:null,width:0,height:0};this.av=[]};gvjs_.move=function(a,b){this.av.push(["M",a,b]);return this};gvjs_.line=function(a,b){this.av.push(["L",a,b]);return this};
gvjs_.arc=function(a,b,c,d,e,f,g){e=gvjs_4q(e);f=gvjs_4q(f);this.av.push(["GVIZARC",a,b,c,d,e,f,Number(g)]);return this};gvjs_.curve=function(a,b,c,d,e,f){this.av.push(["C",a,b,c,d,e,f]);return this};gvjs_.close=function(){this.av.push(["Z"]);return this};function gvjs_6q(a){var b=gvjs_3q(a);a=b.Da(gvjs_ap)||0;var c=b.Da(gvjs_bp)||0,d=b.Da(gvjs_cp)||0,e=b.Da(gvjs_dp)||0,f=b.Da(gvjs_5o)||0,g=b.Da(gvjs_6o)||0,h=b.Da(gvjs_7o)||0;b=b.Da(gvjs_8o)||0;return!!(a||c||d||e||f||g||h||b)}
function gvjs_7q(a){var b=gvjs_3q(a),c=gvjs_F(b,gvjs_9o,0),d=gvjs_F(b,gvjs_$o,0),e=gvjs_F(b,gvjs_ap,c),f=gvjs_F(b,gvjs_bp,d),g=gvjs_F(b,gvjs_cp,c),h=gvjs_F(b,gvjs_dp,d),k=gvjs_F(b,gvjs_5o,c),l=gvjs_F(b,gvjs_6o,d);c=gvjs_F(b,gvjs_7o,c);d=gvjs_F(b,gvjs_8o,d);var m=gvjs_F(b,gvjs_Zd),n=gvjs_F(b,gvjs_8c),p=gvjs_F(b,"x");b=gvjs_F(b,"y");p=0<=m?p:p+m;b=0<=n?b:b+n;m=Math.abs(m);n=Math.abs(n);if(e+g>m){var q=m/(e+g);e*=q;f*=q;g*=q;h*=q}k+c>m&&(q=m/(k+c),k*=q,l*=q,c*=q,d*=q);f+l>n&&(q=n/(f+l),e*=q,f*=q,k*=
q,l*=q);h+d>n&&(q=n/(h+d),g*=q,h*=q,c*=q,d*=q);return(new gvjs_5q(a.tc)).move(p+m-g,b).arc(p+m-g,b+h,g,h,270,0,!0).line(p+m,b+n-d).arc(p+m-c,b+n-d,c,d,0,90,!0).line(p+k,b+n).arc(p+k,b+n-l,k,l,90,180,!0).line(p,b+f).arc(p+e,b+f,e,f,180,270,!0).close()};function gvjs_8q(a){for(var b=0,c=arguments.length;b<c;b++)if(null!=arguments[b])return arguments[b]}
function gvjs_9q(a,b,c,d){gvjs_$q(a,b,c,d);gvjs_ar(a,b,c,d);gvjs_br(a,b,c,d);gvjs_cr(a,b,c,d);gvjs_dr(a,b,c,d);gvjs_er(a,b,c,d);gvjs_fr(a,b,c,d);var e=gvjs_3q(c),f=gvjs_F(e,"clip.width"),g=gvjs_F(e,"clip.height");if(f&&g){var h=gvjs_F(e,"clip.x",0);e=gvjs_F(e,"clip.y",0);var k=["clip",h,e,f,g].join(),l=c.Ir;if(c=a.l2(k,l))n=c.getAttribute(gvjs_9c);else{var m=gvjs_sl();c=m.createElementNS(gvjs_Ep,"clipPath");var n=a.UY();c.setAttribute(gvjs_9c,n);m=m.createElementNS(gvjs_Ep,gvjs_Qp);m.setAttribute("x",
h);m.setAttribute("y",e);m.setAttribute(gvjs_Zd,f);m.setAttribute(gvjs_8c,g);c.appendChild(m);a.X3(k,c,l);for(a=d;a.nodeName!==gvjs_$p;)a=a.parentNode;a=a.querySelector(gvjs_gp)||a;a.insertBefore(c,a.firstChild)}b.setAttribute(gvjs_4o,gvjs_eq+n+")")}else b.hasAttribute(gvjs_4o)&&b.removeAttribute(gvjs_4o)}
function gvjs_ar(a,b,c,d){gvjs_gr(a,b,c,d,!1);a=gvjs_8q(c.style(gvjs_np),c.style(gvjs_pp),c.style(gvjs_lp));typeof a===gvjs_j||typeof a===gvjs_f?b.setAttribute(gvjs_lp,a):null===a&&b.removeAttribute(gvjs_lp)}function gvjs_br(a,b,c){a=gvjs_8q(c.style(gvjs_op),c.style(gvjs_qp),c.style(gvjs_mp));typeof a===gvjs_j||typeof a===gvjs_f?b.setAttribute(gvjs_mp,a):null===a&&b.removeAttribute(gvjs_mp)}
function gvjs_cr(a,b,c,d){gvjs_gr(a,b,c,d,!0);a=gvjs_8q(c.style(gvjs_4p),c.style(gvjs_7p),c.style(gvjs_1p));typeof a===gvjs_j||typeof a===gvjs_f?b.setAttribute(gvjs_1p,a):null===a&&b.removeAttribute(gvjs_1p)}function gvjs_dr(a,b,c){a=gvjs_8q(c.style(gvjs_5p),c.style(gvjs_8p),c.style(gvjs_2p));typeof a===gvjs_j||typeof a===gvjs_f?b.setAttribute(gvjs_2p,a):null===a&&b.removeAttribute(gvjs_2p)}
function gvjs_er(a,b,c){a=gvjs_8q(c.style(gvjs_6p),c.style(gvjs_9p),c.style(gvjs_3p));typeof a===gvjs_j||typeof a===gvjs_f?b.setAttribute(gvjs_3p,a):null===a&&b.removeAttribute(gvjs_3p)}function gvjs_$q(a,b,c){a=c.style(gvjs_Mp);typeof a===gvjs_j||typeof a===gvjs_f?b.setAttribute(gvjs_Mp,a):null===a&&b.removeAttribute(gvjs_Mp)}
function gvjs_gr(a,b,c,d,e){var f=gvjs_3q(c),g=e?gvjs_1p:gvjs_lp,h=f.st(g+".gradient.from"),k=f.st(g+".gradient.to");e=b.getAttribute(g);if(h&&k){var l=gvjs_lq(f,g+".gradient.x1",gvjs_Lo),m=gvjs_lq(f,g+".gradient.y1",gvjs_Lo),n=gvjs_lq(f,g+".gradient.x2",gvjs_Mo),p=gvjs_lq(f,g+".gradient.y2",gvjs_Lo);f=[gvjs_zp,h,k,l,m,n,p].join();var q=c.Ir;if(c=a.l2(f,q))g=c.getAttribute(gvjs_9c);else{var r=gvjs_sl();c=r.createElementNS(gvjs_Ep,gvjs_Ip);g=a.UY();c.setAttribute(gvjs_9c,g);c.setAttribute("x1",l);
c.setAttribute("y1",m);c.setAttribute("x2",n);c.setAttribute("y2",p);l=r.createElementNS(gvjs_Ep,gvjs_0p);l.setAttribute("stop-color",h);l.setAttribute(gvjs_Lp,gvjs_Lo);h=r.createElementNS(gvjs_Ep,gvjs_0p);h.setAttribute("stop-color",k);h.setAttribute(gvjs_Lp,gvjs_Mo);c.appendChild(l);c.appendChild(h);a.X3(f,c,q);for(a=d;a.nodeName!==gvjs_$p;)a=a.parentNode;a=a.querySelector(gvjs_gp)||a;a.insertBefore(c,a.firstChild)}a=gvjs_eq+g+")";e!==a&&b.setAttribute(gvjs_lp,a)}else e&&e.substr(0,5)===gvjs_eq&&
b.removeAttribute(g)}
function gvjs_fr(a,b,c,d){var e=gvjs_3q(c),f=gvjs_lq(e,gvjs_Wp,0),g=gvjs_lq(e,gvjs_Vp,0);if(f||g){var h=e.st("shadow.xOffset")||e.st("shadow.x-offset")||e.st(gvjs_Xp)||0,k=e.st("shadow.yOffset")||e.st("shadow.y-offset")||e.st(gvjs_Yp)||0;e=[gvjs_1o,f,g,h,k].join();var l=c.Ir,m=a.l2(e,l);if(m)c=m.getAttribute(gvjs_9c);else{var n=gvjs_sl();m=n.createElementNS(gvjs_Ep,gvjs_rp);m.setAttribute("x","-100%");m.setAttribute("y","-100%");m.setAttribute(gvjs_Zd,"300%");m.setAttribute(gvjs_8c,"300%");c=a.UY();
m.setAttribute(gvjs_9c,c);var p=n.createElementNS(gvjs_Ep,gvjs_jp);p.setAttribute(gvjs_Fp,"SourceAlpha");p.setAttribute("stdDeviation",f);f=n.createElementNS(gvjs_Ep,"feOffset");f.setAttribute("dx",h);f.setAttribute("dy",k);if(null!=g){var q=n.createElementNS(gvjs_Ep,gvjs_ip);var r=n.createElementNS(gvjs_Ep,"feFuncA");r.setAttribute(gvjs_Vd,gvjs_Hp);r.setAttribute("slope",g)}g=n.createElementNS(gvjs_Ep,"feMerge");h=n.createElementNS(gvjs_Ep,gvjs_kp);n=n.createElementNS(gvjs_Ep,gvjs_kp);n.setAttribute(gvjs_Fp,
"SourceGraphic");m.appendChild(p);m.appendChild(f);null!=r&&(q.appendChild(r),m.appendChild(q));g.appendChild(h);g.appendChild(n);m.appendChild(g);a.X3(e,m,l);for(a=d;a.nodeName!==gvjs_$p;)a=a.parentNode;a=a.querySelector(gvjs_gp)||a;a.insertBefore(m,a.firstChild)}a=b.getAttribute(gvjs_rp);d=gvjs_eq+c+")";a!==d&&b.setAttribute(gvjs_rp,d)}else b.hasAttribute(gvjs_rp)&&b.removeAttribute(gvjs_rp)}
var gvjs_pda={"fill.color":gvjs_ar,fillColor:gvjs_ar,fill:gvjs_ar,"fill.gradient.from":gvjs_ar,"fill.gradient.to":gvjs_ar,"fill.gradient.x1":gvjs_ar,"fill.gradient.y1":gvjs_ar,"fill.gradient.x2":gvjs_ar,"fill.gradient.y2":gvjs_ar,"fill.opacity":gvjs_br,fillOpacity:gvjs_br,"fill-opacity":gvjs_br,height:function(a,b,c){a=gvjs_F(gvjs_3q(c),gvjs_8c);b.setAttribute(gvjs_8c,a)},opacity:gvjs_$q,"shadow.radius":gvjs_fr,"shadow.opacity":gvjs_fr,"shadow.xOffset":gvjs_fr,"shadow.x-offset":gvjs_fr,"shadow.xoffset":gvjs_fr,
"shadow.yOffset":gvjs_fr,"shadow.y-offset":gvjs_fr,"shadow.yoffset":gvjs_fr,"stroke.color":gvjs_cr,strokeColor:gvjs_cr,stroke:gvjs_cr,"stroke.gradient.from":gvjs_cr,"stroke.gradient.to":gvjs_cr,"stroke.gradient.x1":gvjs_cr,"stroke.gradient.y1":gvjs_cr,"stroke.gradient.x2":gvjs_cr,"stroke.gradient.y2":gvjs_cr,"stroke.opacity":gvjs_dr,strokeOpacity:gvjs_dr,"stroke-opacity":gvjs_dr,"stroke.width":gvjs_er,strokeWidth:gvjs_er,"stroke-width":gvjs_er,width:function(a,b,c){a=gvjs_F(gvjs_3q(c),gvjs_Zd);b.setAttribute(gvjs_Zd,
a)},x:function(a,b,c){a=gvjs_F(gvjs_3q(c),"x");b.setAttribute("x",a)},y:function(a,b,c){a=gvjs_F(gvjs_3q(c),"y");b.setAttribute("y",a)}};function gvjs_hr(a,b,c,d,e,f){f=f||{};return(c=f[c]||gvjs_pda[c])?(c(a,b,d,e),!0):!1};var gvjs_ir={applyX:function(a,b,c){a=gvjs_3q(c).Da("x");null!=a&&b.setAttribute("cx",a)},applyY:function(a,b,c){a=gvjs_3q(c).Da("y");null!=a&&b.setAttribute("cy",a)},r6:function(a,b,c){a=gvjs_3q(c).Da("r");null!=a&&b.setAttribute("r",a)}};gvjs_ir.lA={r:gvjs_ir.r6,x:gvjs_ir.applyX,y:gvjs_ir.applyY};
gvjs_ir.draw=function(a,b,c,d){var e=gvjs_sl();d=d||e.createElementNS(gvjs_Ep,gvjs_3o);gvjs_ir.applyX(a,d,b);gvjs_ir.applyY(a,d,b);gvjs_ir.r6(a,d,b);gvjs_9q(a,d,b,c);c&&d.parentNode!==c&&c.appendChild(d);return d};gvjs_ir.og=function(a,b,c,d,e){if(!gvjs_hr(a,e,c,b,d,gvjs_ir.lA))throw'unknown property on circle "'+c+'".';};var gvjs_jr={applyX:function(a,b,c){a=gvjs_F(gvjs_3q(c),"x");b.setAttribute("cx",a)},applyY:function(a,b,c){a=gvjs_F(gvjs_3q(c),"y");b.setAttribute("cy",a)},s6:function(a,b,c){a=gvjs_F(gvjs_3q(c),"rx");b.setAttribute("rx",a)},t6:function(a,b,c){a=gvjs_F(gvjs_3q(c),"ry");b.setAttribute("ry",a)}};gvjs_jr.lA={x:gvjs_jr.applyX,y:gvjs_jr.applyY,rx:gvjs_jr.s6,ry:gvjs_jr.t6};
gvjs_jr.draw=function(a,b,c,d){var e=gvjs_sl();d=d||e.createElementNS(gvjs_Ep,gvjs_hp);gvjs_jr.applyX(a,d,b);gvjs_jr.applyY(a,d,b);gvjs_jr.s6(a,d,b);gvjs_jr.t6(a,d,b);gvjs_9q(a,d,b,c);c&&d.parentNode!==c&&c.appendChild(d);return d};gvjs_jr.og=function(a,b,c,d,e){if(!gvjs_hr(a,e,c,b,d,gvjs_jr.lA))throw gvjs_dq+c+'".';};var gvjs_kr={v6:function(a,b,c){a=gvjs_F(gvjs_3q(c),"x1");b.setAttribute("x1",a)},x6:function(a,b,c){a=gvjs_F(gvjs_3q(c),"y1");b.setAttribute("y1",a)},w6:function(a,b,c){a=gvjs_F(gvjs_3q(c),"x2");b.setAttribute("x2",a)},y6:function(a,b,c){a=gvjs_F(gvjs_3q(c),"y2");b.setAttribute("y2",a)}};gvjs_kr.lA={x1:gvjs_kr.v6,x2:gvjs_kr.w6,y1:gvjs_kr.x6,y2:gvjs_kr.y6};
gvjs_kr.draw=function(a,b,c,d){var e=gvjs_sl();d=d||e.createElementNS(gvjs_Ep,gvjs_d);gvjs_kr.v6(a,d,b);gvjs_kr.w6(a,d,b);gvjs_kr.x6(a,d,b);gvjs_kr.y6(a,d,b);gvjs_9q(a,d,b,c);c&&d.parentNode!==c&&c.appendChild(d);return d};gvjs_kr.og=function(a,b,c,d,e){if(!gvjs_hr(a,e,c,b,d,gvjs_kr.lA))throw gvjs_dq+c+'".';};function gvjs_lr(a,b,c,d){var e=gvjs_sl();e=d||e.createElementNS(gvjs_Ep,gvjs_Np);d||e.setAttribute("d",gvjs_mr(c));gvjs_9q(a,e,c,b);return e}
function gvjs_mr(a){a=a.av;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];if("GVIZARC"===e[0]){var f=e,g=Number(f[1]),h=Number(f[2]);e=Number(f[3]);var k=Number(f[4]),l=gvjs_4q(Number(f[5])),m=gvjs_4q(Number(f[6]));f=!!Number(f[7]);270===l&&0===m?e="A "+e+" "+k+gvjs_Ho+(e+g)+" "+h:180===l&&270===m?e="A "+e+" "+k+gvjs_Ho+g+" "+(h-k):0===l&&90===m?e="A "+e+" "+k+gvjs_Ho+g+" "+(h+k):90===l&&180===m?e="A "+e+" "+k+gvjs_Ho+(g-e)+" "+h:(g+=Math.cos(m/180*Math.PI)*e,h+=Math.sin(m/180*Math.PI)*k,l=f?m-l:
l-m,0>l&&(l+=360),e="A "+e+" "+k+" 0 "+Number(180<l)+" "+Number(f)+" "+g+" "+h)}else e=e.join(" ");b.push(e)}return b.join(" ")};var gvjs_nr={draw:function(a,b,c,d){var e=b.style(gvjs_9o),f=b.style(gvjs_$o),g=gvjs_3q(b),h=gvjs_F(g,gvjs_Zd),k=gvjs_F(g,gvjs_8c),l=gvjs_F(g,"x");g=gvjs_F(g,"y");l=0<=h?l:l+h;g=0<=k?g:g+k;h=Math.abs(h);k=Math.abs(k);if(typeof e===gvjs_f&&typeof f===gvjs_f||!gvjs_6q(b)){var m=gvjs_sl();d=d||m.createElementNS(gvjs_Ep,gvjs_Qp);d.setAttribute("x",l);d.setAttribute("y",g);d.setAttribute(gvjs_Zd,h);d.setAttribute(gvjs_8c,k);null!=e&&typeof e===gvjs_f&&d.setAttribute("rx",e);null!=f&&typeof f===gvjs_f&&
d.setAttribute("ry",f);gvjs_9q(a,d,b,c)}else b=gvjs_7q(b),d=gvjs_lr(a,c,b,d);c&&d.parentNode!==c&&c.appendChild(d);return d},og:function(a,b,c,d,e){if(!gvjs_hr(a,e,c,b,d))switch(c){case gvjs_9o:case gvjs_$o:case gvjs_ap:case gvjs_bp:case gvjs_cp:case gvjs_dp:case gvjs_5o:case gvjs_6o:case gvjs_7o:case gvjs_8o:var f=gvjs_6q(b),g=e.tagName.toLowerCase();if(g===gvjs_Np&&!f||g===gvjs_Qp&&f)return gvjs_nr.draw(a,b,d);g===gvjs_Np?(a=gvjs_7q(b),a=gvjs_mr(a),e.setAttribute("d",a)):c===gvjs_9o?e.setAttribute("rx",
gvjs_F(gvjs_3q(b),gvjs_9o)):c===gvjs_$o&&e.setAttribute("ry",gvjs_F(gvjs_3q(b),gvjs_$o));break;default:throw'unknown property on rect "'+c+'".';}}};var gvjs_or={FM:function(a,b,c){a=c.style(gvjs_tp)||c.style(gvjs_vp)||c.style(gvjs_wp);b.style.fontFamily=typeof a===gvjs_j?a:""},tV:function(a,b,c){a=c.style(gvjs_up)||c.style(gvjs_xp);b.style.fontSize=typeof a===gvjs_f?a+gvjs_U:typeof a===gvjs_j?a:""},uV:function(a,b,c){a=c.style("font.weight")||c.style("fontWeight");b.style.fontWeight=typeof a===gvjs_j||typeof a===gvjs_f?String(a):""},p6:function(a,b,c){!0===c.style(gvjs_Gp)?b.style.fontStyle=gvjs_Gp:b.style.fontStyle=""},u6:function(a,b,c){!0===
c.style(gvjs_cq)?b.style.textDecoration=gvjs_cq:b.style.textDecoration=""}};gvjs_or.lA={"font.family":gvjs_or.FM,fontFamily:gvjs_or.FM,fontName:gvjs_or.FM,"font.size":gvjs_or.tV,fontSize:gvjs_or.tV,"font.weight":gvjs_or.uV,fontWeight:gvjs_or.uV,italic:gvjs_or.p6,underline:gvjs_or.u6};
gvjs_or.Sla=function(a,b,c,d,e,f,g){var h=gvjs_sl();e=e&&e.tagName===gvjs_k?e:h.createElementNS(gvjs_Ep,gvjs_k);e.textContent=c;c=gvjs_3q(d);e.setAttribute("x",null==f?gvjs_lq(c,"x"):f);e.setAttribute("y",null==g?gvjs_lq(c,"y"):g);e.setAttribute(gvjs_Md,"cursor:default;-webkit-user-select:none;-moz-osx-font-smoothing:grayscale;");e.style.webkitFontSmoothing="antialiased";gvjs_9q(a,e,d,b);gvjs_or.p6(a,e,d);gvjs_or.u6(a,e,d);gvjs_or.FM(a,e,d);gvjs_or.tV(a,e,d);gvjs_or.uV(a,e,d);return e};
gvjs_or.bna=function(a,b,c,d){var e=b.style("lineSpacing")||b.style("line-spacing")||0,f=gvjs_3q(b),g=gvjs_D(f,gvjs_k,""),h=-1==gvjs_qq(g,void 0)&&gvjs_x;typeof g===gvjs_j&&(g=g.split("\n"));var k=gvjs_F(f,"y",0),l=!0;1===g.length&&(g=g[0],l=!1);a=gvjs_or.Sla(a,c,l?"":g,b,d,gvjs_F(f,"x",0),k);c&&a.parentNode!==c&&c.appendChild(a);c=[];if(l)for(b=gvjs_sl(),d=0,k=g.length;d<k;d++){var m=b.createElementNS(gvjs_Ep,"tspan");m.textContent=g[d];m.setAttribute(gvjs_Pp,!0);m.setAttribute("x",gvjs_lq(f,"x"));
m.setAttribute("y",gvjs_lq(f,"y"));var n=a.getBBox().height;0<d&&(n+=e);m.setAttribute("dy",n+gvjs_U);a.appendChild(m);c.push(m)}h&&(a.setAttribute("dir",gvjs_Up),a.setAttribute(gvjs_aq,gvjs_T));return{group:a,lines:l?c:[a]}};
gvjs_or.draw=function(a,b,c,d){c=gvjs_or.bna(a,b,c,d);a=c.lines;c=c.group;d=Math.max(0,Math.min(1,b.style(gvjs_Bp)||0));if(isNaN(d)||!isFinite(d))d=0;var e=b.style(gvjs_fq);if(typeof e===gvjs_f){if(e=Math.max(0,Math.min(1,e)),isNaN(e)||!isFinite(e))e=0}else e=gvjs__o;var f=c.getBBox(),g=b.style("y")-f.y;var h="tspan"===a[a.length-1].tagName.toLowerCase()?a[a.length-1].getBoundingClientRect().top-c.getBoundingClientRect().top:a[a.length-1].getBBox().y-f.y;var k=b.style("y");if(null==k)return c;if(typeof e===
gvjs_f)k=k+g-f.height*e;else if(e===gvjs__o)k=k+g-h;else throw"Unrecognized valign value: "+e;c.setAttribute("y",k);e=0;for(f=a.length;e<f;e++)g=a[e],g.setAttribute("dx",-g.getComputedTextLength()*d+gvjs_U),g.setAttribute("y",k);a=b.style(gvjs_Sp);null!=a&&0!=a&&c.setAttribute(gvjs_bq,gvjs_Tp+a+" "+b.style("x")+" "+b.style("y")+")");return c};
gvjs_or.og=function(a,b,c,d,e){var f="x"===c||"y"===c;if(f||!gvjs_hr(a,e,c,b,d,gvjs_or.lA))if(c===gvjs_k||c===gvjs_Bp||c===gvjs_fq||f){for(;e&&e.firstChild;)e.removeChild(e.firstChild);a=gvjs_or.draw(a,b,d,e);if(e!==a)throw"error redrawing text";}else throw'error redrawing text element with changed property "'+c+'".';};var gvjs_pr={draw:function(a,b,c,d){var e=gvjs_sl();d=d||e.createElementNS(gvjs_Ep,"g");gvjs_9q(a,d,b,c);c&&d.parentNode!==c&&c.appendChild(d);return d},og:function(a,b,c,d){a=gvjs_pr.draw(a,b,c,d);d!==a&&b.getContext().fireEvent("add",[b,a,!1])}};var gvjs_qda={Circle:gvjs_ir,Ellipse:gvjs_jr,Line:gvjs_kr,Path:{draw:function(a,b,c,d){a=gvjs_lr(a,c,b,d);c&&a.parentNode!==c&&c.appendChild(a);return a},og:function(a,b,c,d,e){if(!gvjs_hr(a,e,c,b,d))throw gvjs_dq+c+'".';}},Rect:gvjs_nr,Text:gvjs_or,Group:gvjs_pr};
