//# sourceURL=J_ALTUI_loc_fr.js
// http://192.168.1.16:3480/data_request?id=lr_ALTUI_Handler&command=home
// This program is free software: you can redistribute it and/or modify
// it under the condition that it is for private or home useage and 
// this whole comment is reproduced in the source code file.
// Commercial utilisation is not authorized without the appropriate
// written agreement from amg0 / alexis . mermet @ gmail . com
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 

Localization.init( {
	"Home":"Maison",
	"Away":"Distant",
	"Night":"Nuit",
	"Vacation":"Vacances",
	"Room": "Pièce",
	"Rooms": "Pièces",
	"Device": "Périphérique",
	"Devices": "Périphériques",
	"Control Panel": "Contrôle",
	"Scenes": "Scènes",
	"Scene Edit": "Édition de Scène",
	"Plugins": "Plugins",
	"Custom Pages": "Pages Perso",
	"Edit Pages": "Éditer les pages",
	"Credits": "Crédits",
	"LuaTest": "LuaTest",
	"LuaStart": "LuaStart",
	"Optimize": "Optimise",
	"Editor": "Éditeur",
	"Close": "Fermer",
	"Custom Pages Editor": "Éditeur de Pages Perso",
	"Lua Startup": "Démarrage Lua",
	"Lua Code Test":"Test du code Lua",
	"Options": "Options",
	"Unmuted,Muted":"Normal,Mute",
	"Normal,Debug":"Normal,Debug",
	"Up":"Haut",
	"Stop":"Stop",
	"Down":"Bas",
	"Open":"Ouvrir",
	"Unlock,Lock":"Déverrouiller,Vérouiller",
	"Bypass,Arm":"Libre,Armé",
	"Use Custom Pages":"Utiliser Pages Perso",
	"Edit Custom Pages":"Édition Pages Perso",
	"More":"Plus",
	"Less":"Moins",
	"Remote Access Login":"Accès à Distance",
	"Reload Luup Engine":"Redémarrer Moteur Luup",
	"Lua Startup Code":"Code Démarrage Lua",
	"Lua Test Code":"Test du code Lua",
	"Localization":"Localisation",
	"Misc":"Divers",
	"Create":"Créer",
	"Runs in all modes, or in selected mode": "S'exécute dans tous les modes, ou dans le mode sélectionné",
	"Run" : "Exécuter",
	"OFF,ON":"OFF,ON",
	"Working":"Travail",
	"Holiday":"Vacances",
	"Wind":"Vent",
	"Are you sure you want to delete scene ({0})":"Étes-vous sûr de vouloir supprimer la scène ({0})",
	"Controller {0} is busy, be patient.":"Le Controleur {0} est occupé, soyez patient ...",
	"Submit":"Soumettre",
	"Save Changes":"Sauvegarder les modifications",
	"Notification":"Notification",
	"Triggers":"Évènements",
	"Timers":"Timers",
	"Actions":"Actions",
	"Lua":"Lua",
	"OffLabel":"Étiquette Off",
	"OnLabel":"Étiquette On",
	"Label":"Étiquette",
	"Min":"Min",
	"Green":"Vert",
	"Orange":"Orange",
	"Red":"Rouge",
	"Max":"Max",
	"Ticks":"Traits",
	"TimerName":"Nom du Timer",
	"TimerType":"Type de Timer",
	"TimerInterval":"Intervalle du Timer",
	"TimerDayOfWeek":"Timer Jour De Semaine",
	"TimerDayOfMonth":"Timer Jour Du Mois",
	"TriggerName":"Evènement Nom",
	"Delay":"Délai",
	"Action to switch OFF":"Action pour Éteindre",
	"Action to switch ON":"Action pour Allumer",
	"Action":"Action",
	"Device Variable Properties":"Propriétés du Périphérique",
	"Parameters":"Paramètres",
	"Value":"Valeur",
	"Variable":"Variable",
	"Attributes":"Attributs",
	"Load":"Charge",
	"Info":"Info",
	"Image":"Image",
	"Run Scene":"Exécute Scène",
	"Edit":"Edit",
	"Camera":"Caméra",
	"On Off":"On Off",
	"Gauge":"Jauge",
	"Device Icon":"Icône",
	"Scene":"Scène",
	"Multi State":"Multi Etats",
	"Mo":"Lu",
	"Tu":"Ma",
	"We":"Me",
	"Th":"Je",
	"Fr":"Ve",
	"Sa":"Sa",
	"Su":"Di",
	"At a certain time of day":"A un moment de la journée",
	"At sunrise":"Au Lever du soleil",
	"Before sunrise":"Avant le Lever du soleil",
	"After sunrise":"Après le Lever du soleil",
	"At sunset":"Au Coucher du Soleil",
	"Before sunset":"Avant le Coucher du Soleil",
	"After sunset":"Après le Coucher du Soleil",
	"Timer":"Programmation",
	"**Illegal**":"**Interdit**",
	"interval":"intervalle",
	"day of week":"Jour de la Semaine",
	"day of month":"Jour du Mois",
	"absolute":"Heure Fixe",
	"Search":"Chercher",
	"Remove":"Supprimer",
	"No Match":"Aucun",
	"Reboot Vera":"Redémarrer Vera",
	"This plugin is a work in progress, it will continuously evolve over time.":"Ce Plugin est un projet en cours, il continue d'évoluer au fil du temps.",
	"You may check out the evolutions on the Micasaverde <a href='http://forum.micasaverde.com/index.php/topic,30310.msg216129.html#msg216129'>Forum</a>":"Vous pouvez suivre les évolutions sur <a href='http://forum.micasaverde.com/index.php/topic,30310.msg216129.html#msg216129'>Forum</a> Micasaverde",
	"All":"Tous",
	"No Room":"Pas de Pièce",
	"Device creation failed":"Échec de la création du Périphérique",
	"Device {0} created successfully":"Périphérique {0} créé avec succès",
	"Filter":"Filtre",
	"Category":"Catégorie",
	"Could not create Room":"Échec de création de la pièce",
	"New Page":"Nouvelle Page",
	"Page Properties":"Propriétés",
	"Delete this Page":"Supprimer cette page",
	"Save All Pages":"Sauver les pages",
	"Files":"Fichiers",
	"Name":"Nom",
	"Version":"Version",
	"Update":"Mise à jour",
	"Uninstall":"Désinstaller",
	"Messages":"Messages",
	"zWave Network":"Réseau zWave",
	"ZWave":"ZWave",
	"Localize":"Localiser",
	"Localizations":"Localisations",
	"Power Chart":"Graphique Puissance",
	"Power":"Puissance",
	"Localization information":"Information de Localisation",
	"Mesh":"Couverture",
	"Order By":"Trier par",
	"Reset Poll Counters":"Remise a Zéro des compteurs",
	"Parent/Child Network":"Réseau Parent/Enfant",
	"Parent/Child":"Parent/Enfant",
	"Drag and Drop to add/move/delete controls. use Ctrl+Click or lasso to select multiple controls":"Déplacer/Glisser pour rajouter ou enlever des contrôles. utiliser Ctrl+Click ou le lasso pour sélectionner plusieurs éléments",
	"Drag and Drop to fix the position of a node. Simple Click to open or collapse a parent node, Shift Click to free a fixed node":"Déplacer/Glisser pour fixer la position d'un nœud. Cliquer pour ouvrir ou refermer un nœud parent, Shift click pour libérer un nœud fixé",
	"Network Quality":"Qualité du Réseau",
	"Quality":"Qualité",
	"Show":"Voir",
	"zWave Routes":"Routes zWave",
	"Scene Action Group":"Groupe d'Action",
	"Pause Scene":"Pause Scene",
	"Trigger Restriction":"Evènement Limité",
	"Restrict trigger based on certain times":"Limite les Évènements à une certaine plage horaire",
	"Start Time":"Heure de début",
	"Stop Time":"Heure de fin",
	"zWave Routes":"Routes zWave ",
	"zWaveRoutes":"zWaveRoutes",
	"error happened during decoding triggers, probable duplicate ID or invalid format":"une erreur est intervenue pendant l'affichage des Événements, probablement un ID en double ou un format invalide",
	"TblDevices":"TblDevices",
	"Table Devices":"Table Périphériques",
	"Update Neighbors":"Mise a jour des Voisins",
	"Update Neighbors succeeded":"Mise a jour des Voisins réussie",
	"Copy to clipboard":"Copier dans le presse-papiers",
	"Data copied in clipboard":"Données copiées dans le presse-papiers",
	"Code execution succeeded":"Exécution réussie",
	"Code execution failed":"Exécution avec erreur",
	"Reboot request succeeded":"Succès de la requête de Reboot",
	"Reboot request failed":"Echec de la requête de Reboot",
	"Favorite":"Favori",
	"Favorites":"Favoris",
	"Variables":"Variables",
	"Used in":"Utilisé dans",
	"OsCommand":"CommandeOS",
	"Disk Usage":"Utilisation Disque",
	"Free Space":"Espace Libre",
	"Plugin Files":"Fichier des Plugins",
	"Log Sizes":"Taille des Logs",
	"OS Command":"Commande OS",
	"Frequent Commands":"Commandes Fréquentes",
	"Output":"Sortie",
	"Os Command execution succeeded":"L'exécution de la commande Os a réussie",
	"Version number or empty for latest official version":"Numéro de Version ou vide pour la dernière version officielle",
	"Update Plugin succeeded, be patient Luup will reload":"La mise a jour est demandée, Patience, Luup va redémarrer",
	"Enter a Vera OS ( Unix ) command, the stdout will be returned and displayed below":"Tapez une commande Vera OS (Unix), la sortie stdout sera affichée ci dessous",
	"Os Command execution on vera failed.":"L'exécution de la commande OS a échoué.",
	"failed to execute":"Échec d'exécution",
	"Are you Sure ?":"Êtes-vous sûr ?",
	"Yes":"Oui",
	"Are you sure you want to delete device ({0})":"Voulez vous vraiment supprimer le périphérique ({0})",
	"Are you sure you want to delete room":"Voulez-vous vraiment supprimer la pièce",
	"Are you sure you want to uninstall this plugin #{0} and all its created devices":"Voulez vous vraiment désinstaller ce plugin #{0} et tous les périphériques qu'il a créé",
	"a newer version #{0} of ALTUI is available, do you want to upgrade ?":"une nouvelle version #{0} de ALTUI est disponible, voulez vous mettre a jour ?",
	"Question":"Question",
	"Options":"Options",
	"Show Video Thumbnail in Local mode":"Voir les vignettes vidéo en local",
	"Cache Control":"Contrôle du Cache",
	"Custom Pages Control":"Contrôle des Pages Utilisateurs",
	"Refresh":"Rafraichir",
	"Search Logs":"Cherche Logs",
	"Tail Logs":"Fin Logs",
	"label":"Étiquette",
	"command":"commande",
	"Add":"Ajouter",
	"Default":"Défaut",
	"Command Parameters":"Paramètres de Commande",
	"Parameter":"Paramètre",
	"Test Code":"Test Code",
	"Panels":"Panneaux",
	"Reports":"Rapports",
	"Evolutions":"Évolutions",
	"History":"Historique",
	"Date":"Date",
	"Old":"Ancien",
	"New":"Nouveau",
	"Scene History":"Historique Scène",
	"Button Label":"Étiquette Bouton",
	"Color":"Couleur",
	"Ran Scene #{0} successfully":"Exécution avec succès de la Scène #{0}",
	"Not used in scenes or workflows":"Pas d'utilisation dans les scènes ou workflows",
	"Controller {0} did not respond":"Le Contrôleur {0} ne répond pas",
	"Option":"Option",
	"Debug":"Debug",
	"All devices":"Tous les périphériques",
	"One Device's States":"Toutes les variables",
	"Variable search":"Cherche Variable",
	"Javascript code":"Code javascript",
	"Debug Tools":"Outils de Debug",
	"Debug Actions":"Actions de Debug",
	"Altui ID":"Altui ID",
	"Variable Name Pattern":"Pattern de Nom de Variable",
	"an error happened during the execution":"Une erreur est survenue pendant l'exécution",
	"Controller":"Controller",
	"Counters have been reset properly":"Les compteurs ont été remis a zéro",
	"do you want to change lua startup code ? if yes, it will generate a Lua reload, be patient...":"Voulez vous vraiment modifier le code Lua de démarrage, LUUP devra redémarrer, soyez patient...",
	"Lua Startup code has been modified":"Le code Lua de démarrage a été modifié avec succès",
	"Header":"Entête",
	"Delay":"Délai",
	"Edited Scene {0} successfully":"La scène {0} est sauvegardée",
	"Notification from {0}":"Notification de {0}",
	"Notify Users":"Notifier ces Utilisateurs",
	"Deleted Scene {0} successfully":"La scène {0} est détruite",
	"Left Buttons are fixed on the page":"Fixer la barre de boutons a gauche",
	"See":"Voir",
	"2-columns Menu's limit":"Limite pour les Menus a 2 colonnes",
	"Find Json":"Chercher Json",
	"Frame":"Cadre",
	"Reload is done":"Redémarrage effectué",
	"Device Triggers":"Evènement de Périphérique",
	"Trigger":"Evènement",
	"Device Variable Watches":"Suivi des Variables de Périphérique",
	"Watch":"Suivi des Variables",
	"Lua Expression with new=newvalue and old=oldvalue":"Expression Lua avec new=nouvelle valeur et old=ancienne valeur",
	"Expression with old new as variables and lua operators like <  >  <= >= == ~=":"Expression avec les variables old,new et les opérateurs logiques Lua comme < > <= >= == ~=",
	"Logs":"Logs",
	"Play":"Jouer",
	"Night,Day":"Nuit,Jour",
	"Show Weather on home page":"Gadget Météo sur la page principale",
	"Weather Temp Unit (UI5)":"Unité de température (UI5)",
	"Watch Formula":"Formule du Suivi de variable",
	"Generated code":"Code Généré",
	"Edit Watch Expression":"Editer l\"expression du Suivi de Variable",
	"Return Result":"Résultat",
	"Console Output":"Sortie Console",
	"Lua execution succeeded":"Exécution Lua réussie",
	"This test code will succeed if it is syntactically correct. It must be the body of a function and can return something. The return object and console output will be displayed)":"La syntaxe de ce code de test doit etre correcte. Cela doit etre le corps d'une fonction et peut retourner une valeur. L'objet de retour et la sortie de la console seront affichés)",
	"H M S part of a timestamp":"partie H M S d'un timestamp",
	"H M S duration in seconds":"duree H M S en secondes",
	"Convert text to number":"Conversion en nombre",
	"Welcome to ALTUI":"Bienvenue dans ALTUI",
	"Use Vera Favorites":"Utiliser les Favoris en mode Vera",
	"Graph":"Graphique",
	"Themes":"Thèmes",
	"Arm":"Armer",
	"Bypass":"Désarmer",
	"Restart":"Redémarrer",
	"On":"On","Off":"Off","Reset":"Reset",
	"Create Device succeeded":"Périphérique créé",
	"Configuration":"Configuration",
	"Deleted Device {0} successfully":"Périphérique {0} effacé avec succès",
	"Reset Theme Override":"Remise a zéro du thème",
	"Preview":"Prévisualiser",
	"Delete":"Effacer",
	"Settings":"Paramètres",
	"Controllers":"Contrôleurs",
	"Support":"Support",
	"TblScenes":"Table Scènes",
	"TblControllers":"Table Contrôleurs",
	"TblWatches":"Table de vues",
	"Save":"Sauver",
	"Frame Properties":"Propriétés du Cadre",
	"Frame Label":"Étiquette du Cadre",
	"Background CSS":"Fond du CSS",
	"IFrame Url":"Url IFrame",
	"Optional, if specified frame will be filled in with this url":"Optionel, affiche une page web si specifiée avec cet URL",
	"Same Room for Devices/Scenes":"Même Pièce pour la page Périphériques/Scènes",
	"Rules":"Règles",
	"Timeline":"Timeline",
	"Table Scenes":"Table Scènes",
	"Use new UI7 behavior for Heater devices":"Utilise le comportement UI7 pour les thermostats",
	"Show all rows in grid tables":"Voir toutes les lignes dans les tables",
	"Table Controllers":"Table Contrôleurs"	,
	"Unregistered version for {0}":"Version non enregistrée pour {0}",
	"Registered Version":"Version Enregistrée",
	"Hide":"Cacher",
	"Value ON":"Valeur ON",
	"Value OFF":"Valeur OFF",
	"Watches":"Variables Suivies",
	"Push to {5}":"Pousser vers {5}",
	"Table Watches":"Table Variables Suivies",
	"Are you sure you want to delete scene watch ({0})":"Etes vous sur de vouloir effacer le déclencheur de la scene ({0})",
	"Are you sure you want to delete data push ({0})":"Etes vous sur de vouloir supprimer le \"data push\" ({0})",
	"Watch Display":"Graphs Variables Suivies",
	"WatchDisplay":"WatchDisplay",
	"Alert - Camera":"Alerte Caméra",
	"Workflows":"Automates",
	"Workflow Pages":"Pages Automates",
	"Workflow":"Automate",
	"Test":"Test",
	"Workflow Editor":"Editeur d'Automate",
	"State":"État",
	"State Properties":"Propriétés d'État",
	"State Name":"Nom d'État",
	"State Actions":"Actions d'État",
	"On Enter":"A l'Entrée",
	"On Exit":"A la Sortie",
	"Link Properties":"Propriétés de Transition",
	"Link Name":"Nom de transition",
	"Link Conditions":"Conditions de transition",
	"Conditions":"Conditions",
	"All conditions must match ( logical AND ) for the transition to happen":"Toutes les conditions doivent etre vraies for que la transition se fasse",
	"Timer Name":"Nom du Timer",
	"Duration":"Durée",
	"Distribute Horizontally":"Distribution Horizontale",
	"Distribute Vertically":"Distribution Verticale",
	"Slider":"Curseur",
	"Workflow Report":"Rapport de Workflow",
	"Upgrade Request succeeded, a Luup reload will happen":"Requete de mise a jour, un redemarrage de Luup est en cours",
	"Invisible":"Invisible",
	"Battery":"Batterie",
	"Zigbee":"Zigbee",
	"Bluetooth":"Bluetooth",
	"Pause Workflow":"Pause Workflow",
	"Report":"Rapport",
	"Copy":"Copier",
	"In Local access mode, show camera in video stream mode":"En mode local, afficher les cameras en mode video stream",
	"ShowVideoThumbnail:In Local access mode, show camera in video stream mode":"ShowVideoThumbnail:En mode local, afficher les cameras en mode video stream",
	"choose whether or not the selection Buttons on the left are scrolling with the page":"Empecher la barre de navigation a gauche de scroller avec la page",
	"FixedLeftButtonBar:choose whether or not the selection Buttons on the left are scrolling with the page":"FixedLeftButtonBar:Empecher la barre de navigation a gauche de scroller avec la page",
	"display or not the weather widget on home page":"Afficher le widget meteo sur la page principale",
	"ShowWeather:display or not the weather widget on home page":"ShowWeather:Afficher le widget meteo sur la page principale",
	"use the same favorites as set on your VERA box but prevent to have different favorites per client device":"Utilise les memes favoris que sur la VERA mais empeche d'avoir des favoris differents par périphérique client",
	"UseVeraFavorites:use the same favorites as set on your VERA box but prevent to have different favorites per client device":"UseVeraFavorites:Utilise les memes favoris que sur la VERA mais empeche d'avoir des favoris differents par périphérique client",
	"keep the same last selected room between the device and the scene pages":"Garder la meme selection de piece pour les pages peripherique et scene",
	"SyncLastRoom:keep the same last selected room between the device and the scene pages":"SyncLastRoom:Garder la meme selection de piece pour les pages peripherique et scene",
	"Fixes the footer at the bottom of the page but could have performance issues on mobile browsers":"Fixe le footer en bas de page mais non recommande sur les peripheriques mobiles",
	"Sticky Footer to bottom":"Footer bloque en bas de page",
	"StickyFooter:Fixes the footer at the bottom of the page but could have performance issues on mobile browsers":"StickyFooter:Fixe le footer en bas de page mais non recommande sur les peripheriques mobiles",
	"technical option to trigger the UI7 behavior for heater":"Option technique pour le comportement UI7 des Thermostats",
	"UseUI7Heater:technical option to trigger the UI7 behavior for heater":"UseUI7Heater:Option technique pour le comportement UI7 des Thermostats",
	"allways show all the lines in the grid tables, or have a row count selector instead":"Montrer toutes les lignes d'une table ou bien par lot",
	"ShowAllRows:allways show all the lines in the grid tables, or have a row count selector instead":"ShowAllRows:Montrer toutes les lignes d'une table ou bien par lot",
	"if a menu has more entries than this number then show the menu entries in 2 columns":"Montrer les menus sur 2 colonnes si le nombre d\"items dépasse ce nombre",
	"Menu2ColumnLimit:if a menu has more entries than this number then show the menu entries in 2 columns":"Menu2ColumnLimit:Montrer les menus sur 2 colonnes si le nombre d items depasse ce nombre",
	"Unit for temperature":"Unité de temprérature",
	"TempUnitOverride:Unit for temperature":"TempUnitOverride:Unité de temprérature",
	"Editor Control":"Contrôle de l\"éditeur",
	"Editor Theme":"Thème de l\"éditeur",
	"Editor font size in pixels":"Taille de caractères de l\"éditeur en pixels",
	"Editor Font Size":"Taille de caractères de l\"éditeur",
	"EditorFontSize:Editor font size in pixels":"EditorFontSize:Taille de caractères de l\"éditeur en pixels",
	"info":"info",
	"Bag":"Panier",
	"Import/Export":"Import/Export",
	"Variables Bag":"Panier de Variables",
	"No data to display":"Pas de donnée à afficher",
	"Schedules":"Échéanciers",
	"Duration (sec)":"Durée (sec)",
	"None":"Rien",
	"Only in the following mode(s)":"Seulement dans le(s) mode(s) suivant(s)",
	"Record":"Enregistrement",
	"Normal,Recorder":"Normal,Enregistre",
	"Are you sure you want to modify this attribute":"Etes vous sur de vouloir modifier cet attribut",
	"License Fees":"Enregistrer ma version",
	"License":"License",
	"Horizontal Slider":"Curseur Horizontal",
	"For non commercial use, ALTUI plugin is free for trial with some limitation on its functionality. To compensate the effort and time spent on regularly improving this project, a registration fee equivalent to <span class='text-info'><mark><b>2€ per month</b></mark></span> is requested for longer term use. You can choose your level of contribution.":"Pour une utilisation non commerciale, ALTUI est gratuit avec presque toutes les fonctionalites sans limitation. Afin de contribuer aux efforts d'amelioration constants du projet, un abonnement modique equivalent à <span class='text-info'><mark><b>2€ par mois</b></mark></span> est demandé pour l utilisation à long terme. Vous pouvez choisir votre contribution et la durée.",
	"Once registered you will get:<ul><li>Access to all the releases and auto update mechanism (not available to non registered users)</li><li>Removal of unregistered welcome message, as well as license message in the footer</li></ul>":"Une fois enregistré, vous aurez accès aux:<ul><li>Nouvelles versions avec le mécanisme de <b>mise à jour automatique</b> réservé aux utilisateurs enregistrés</li><li><b>Absence</b> du message d'alerte de version non enregistrée en haut de page et dans le pied de page</li></ul>",
	"Resellers or Integrators are welcome to contact me for eventual commercial agreements.":"Les revendeurs / intégrateurs qui souhaiteraient utiliser ce logiciel dans leurs solutions peuvent me contacter pour passer un accord commercial.",
	"Check for Updates":"Cherche une mise a jour",
	"Unregistered Version":"Version Non Enregistrée",
	"active":"actif",
	"Device zWave Parameters":"Paramètres module zWave",
	"Lua Editor":"Éditeur Lua",
	"Recording...":"Enregistrement...",
	"Close for 24h":"Fermer pour 24h",
	"Backup Controller":"Sauvegarder",
	"ZWave Heal":"ZWave Heal",
	"ZWave Inclusion":"ZWave Inclusion",
	"ZWave Exclusion":"ZWave Exclusion",
	"Details":"Details",
	"You already have the latest version":"Vous avez déjà une version à jour",
	"Prevent drag and drop of favorites to reorder them":"Empeche le re-agencement des favoris",
	"Lock favorites position":"Fixer la position des favoris",
	"LockFavoritePosition:Prevent drag and drop of favorites to reorder them":"LockFavoritePosition: Empeche de re-ordonner les favoris",
	"Top":"Haut",
	"Page Up":"Page Préc",
	"Page Down":"Page Suiv",
	"Bottom":"Bas",
	"App Store":"App Store","Publish App":"Publier Application","Install":"Installer","Application Store":"Catalogue d'Application",
	"Publish":"Publier","ALT":"ALT","Vera":"Vera","Publish Application":"Publier Application",
	"Contacting Server...":"Connection en cours au Server...",
	"Please go to this page <a href='{1}' target='_blank'>{1}</a> and enter this code : {0}":"Aller sur cette page <a href='{1}' target='_blank'>{1}</a> et entrer ce code : {0}",
	"Select an App":"Selectioner une Application","Publish an App":"Publier une Application",
	"Application":"Application","App ID":"App ID","App Title":"Titre Application",
	"VersionMajor":"VersionMajor","VersionMinor":"VersionMinor","Description":"Description",
	"Icon":"Icon","DeviceFileName":"DeviceFileName","DeviceType":"DeviceType","ImplFile":"ImplFile",
	"GitHub":"GitHub","backup":"backup","default":"default","downloads":"downloads",
	"pattern":"pattern","source":"source","Vera Store":"Vera Store","version":"version","Modify":"Modifier",
	"Refreshing Token...":"Rafraichissement du Token...","Authenticating client device...":"Authentification du client...",
	"Please go to this page <a href='{1}' target='_blank'>{1}</a> and enter this code : <mark>{0}</mark> <div class='altui-plugin-msg2'></div>":"Allez à cette page <a href='{1}' target='_blank'>{1}</a> et entrer ce code : <mark>{0}</mark> <div class='altui-plugin-msg2'></div>",
	"{0} Tentative #{1}/10":"{0} Tentative #{1}/10",
	"Failure after 10 tentatives, try again...":"Echec après 10 tentatives, Ré-essayez...",
	"Select a Version":"Selectionnez une version","Edit Application Properties":"Editez l'application",
	"Instructions":"Instructions","AllowMultiple":"AllowMultiple","AutoUpdate":"AutoUpdate",
	"Version Major":"Version Majeur","Version Minor":"Version Mineur",
	"folders":"repertoires",
	"release":"nom de release",
	"Duration (sec or min-max)":"Durée (sec ou min-max)",
	"Invalid Transition":"Transition Invalide",
	"Transition appears to be empty, you need at least a condition , a schedule or a timer":"La transition est vide, vous devez avoir au moins une condition ou un schedule ou un timer",
	"warning":"attention",
	"Saving workflows":"Sauvegarde des workflows",
	"Smooth Link":"Courbe de lien lissée",
	"Show OS statistics in the footer":"Montre les statistiques OS en pied de page",
	"Show OS Statistics":"Montre les statistiques OS",
	"TopStats:Show OS statistics in the footer":"TopStats:Montre les statistiques OS en pied de page",
	"Errors Warnings":"Errors Warnings",
	"Next Page":"Page Suivante","Prev Page":"Page Précédente",
	"Zoom In":"Zoom +","Zoom Out":"Zoom -","Move Left":"A Gauche","Move Right":"A Droite","Track Now":"Suivre",
	"My Home":"Ma Maison",
	"Sensors":"Détecteurs",
	"Covers":"Volets",
	"Note: MyHome page is limited to 5 items per page for non registered users":"Note: la page MyHome page est limitée à 5 items par page pour les utilisateurs non enregistrés",
	"Save the scene at least once before creating device watches":"Sauver la scène une première fois avant de créer une variable suivie",
	"Back":"Retour",
	"display or not the House mode widget on home page":"Controle l affichage du widget des modes Maison sur la page principale",
	"Show House Mode on home page":"Gadget des modes Maison sur la page principale",
	"ShowHouseMode:display or not the House mode widget on home page":"ShowHouseMode:Controle l affichage du widget des modes Maison sur la page principale",
	"Please be patient, registration will become effective after <mark>1 or 2 business days</mark>. Otherwise contact me with a copy of your page footer":"L'enregistrement de la license peut prendre <mark>1 a 2 jours ouvrés</mark>. Au dela, contactez moi avec une copie d'écran du bas de page svp",
	"Execute Action":"Exécute Action",
	"Start":"Démarre",
	"Cancel":"Annule",
	"Force":"Force",
	"Muted":"Muted",
	"Unmuted":"Unmuted",
	"Pause":"Pause",
	"Scene Trigger Evaluation mode":"Mode d'évaluation des déclencheurs",
	"Create From State":"Créer de l\'état courant",
	"Search Results":"Résultats",
	"Enter a valid device name":"Entrer un nom de périphérique valide",
	"Enter a valid Dxxx.xml file name":"Entrer un fichier Dxxx.xml valide",
	"Enter the device Definition file name":"Entrer le fichier de definition du périphérique",
	"Enter a valid Ixxx.xml file name":"Entrer un fichier Ixxx.xml valide",
	"Enter the device Implementation file name":"Enter the device Implementation file name",
	"Fix Device States":"Fix Device States"	,
	"Users":"Utilisateurs",
	"Are you sure you want to clone scene ({0})":"Voulez vous cloner la scene ({0})",
	"Clone":"Clone",
	"ShowMyHomeImages:Show Images headers in MyHome page cards":"ShowMyHomeImages:Affiche des images dans la page MyHome",
	"Show Images in MyHome page":"Affiche des images dans la page MyHome",
	"UseMasonryInMyHome:Use Masonry layout for cards in MyHome page":"UseMasonryInMyHome:Utilise le placement Masonry pour les cartes de la page MyHome",
	"Use Masonry layout in MyHome page":"Utilise le placement Masonry sur la page MyHome",
	"Monitor Scene":"Scène Monitorée",
	"zWave DB":"zWave DB",
	"Help":"Aide",
	"Unknown Class":"Classe Inconnue",
	"Enter a valid variable number":"Entrer un numéro de variable valide",
	"Loading...":"Chargement...",
	"Do you also want to delete this variable definitively ? ({0})":"Voulez vous définitivement enlever cette variable du périphérique ? ({0})",
	"Create Room succeeded for":"Succès pour la création de",
	"Please go to this page <a href='{1}' target='_blank'>{1}</a> and enter this code : <mark>{0}</mark>":"Allez sur la page <a href='{1}' target='_blank'>{1}</a> et entrer ce code: <mark>{0}</mark>",
	"Please enter a valid element":"Entrer un élement valide svp",
	"Support Ticket":"Ticket de support",
	"No Graphic Url available":"Pas d'url pour le graphique",
	"Poll Success Rate":"Poll Success Rate","No Poll":"No Poll",
	"info-circle":"info-circle",
	"ShowMyHomeImages: Show Images headers in MyHome page cards":"ShowMyHomeImages: Montre les images dans les cartes de la page MyHome",
	"UseMasonryInMyHome: Use Masonry layout for cards in MyHome page":"UseMasonryInMyHome: Utilise le layout Masonry pour les cartes de la page MyHome",
	"ShowVideoThumbnail: In Local access mode, show camera in video stream mode":"ShowVideoThumbnail: en mode local, utilise le stream video pour les caméras",
	"ShowWeather: display or not the weather widget on home page":"ShowWeather: affiche le widget météo sur la page principale",
	"ShowHouseMode: display or not the House mode widget on home page":"ShowHouseMode: affiche le widget Home Mode sur la page principale",
	"ServerSideOptions: use option choices from the vera to share the same options across several ALTUI clients":"ServerSideOptions: Cocher pour partager les memes options sur tous les clients ALTUI",
	"Share options on all ALTUI clients":"Partage les options sur tous les clients ALTUI",
	"UseVeraFavorites: use the same favorites as set on your VERA box but prevent to have different favorites per client device":"UseVeraFavorites: Utilise les favoris de la VERA sur ce client ALTUI",
	"SyncLastRoom: keep the same last selected room between the device and the scene pages":"SyncLastRoom: Garde la piece selectionnée pour les page device / scene",
	"StickyFooter: Fixes the footer at the bottom of the page but could have performance issues on mobile browsers":"StickyFooter: Fixe la position du footer en base de page ( performance impact possible )",
	"UseUI7Heater: technical option to trigger the UI7 behavior for heater":"UseUI7Heater: Option technique pour utiliser le mode UI7 pour les thermostats",
	"ShowAllRows: allways show all the lines in the grid tables, or have a row count selector instead":	"ShowAllRows: affiche toutes les lignes des tables , ou bien un selecteur de taille de table",
	"LockFavoritePosition: Prevent drag and drop of favorites to reorder them":"LockFavoritePosition: Empecher de reordonner les favoris par drag and drop",
	"TopStats: Show OS statistics in the footer":"TopStats: Affiche les statistiques OS dans le footer",
	"Menu2ColumnLimit: if a menu has more entries than this number then show the menu entries in 2 columns":"Menu2ColumnLimit: affiche le menu en 2 colonnes si le nombre de lignes est superieur à cette limite",
	"TempUnitOverride: Unit for temperature":"TempUnitOverride: Unité pour la température",
	"EditorFontSize: Editor font size in pixels":"EditorFontSize: taille des caractères en pixel",
	"Paused":"Pause",
	"ShowClock: The local clock time is displayed in the message bar":"ShowClock: Montre l heure dans la barre de message",
	"Show Clock in Message bar":"Montre l heure dans la barre de message",
	"MyRoom Backgrounds":"Images pour Ma Maison",
	"Graph Pages Control":"Control des pages de graphes",
	"Weather Widget Control":"Controle du Widget Météo",
	"WeatherWidgetButton: open weatherwidget.io to configure widget":"WeatherWidgetButton: ouvrir weatherwidget.io pour la configuration",
	"WeatherWidgetCode: Copy Paste the Widget code here":"WeatherWidgetCode: Copier Coller le code du widget météo",
	"Weather Widget HTML Code":"Code HTML du Widget Météo",
	"Tag Custom Names":"Noms pour les Tags",
	"Tags":"Tags",
	"Add Tag":"Ajouter un Tag"
});

// override rules with localized version
SpeechManager.initRules([
	{r:"(allumer|allume|ouvrir|ouvre).*\\s+(%name%)", t:"device", a:{service:"urn:upnp-org:serviceId:SwitchPower1", action:"SetTarget", params:"{ \"newTargetValue\":1}"}},
	{r:"(éteindre|éteins|fermer|ferme).*\\s+(%name%)", t:"device", a:{service:"urn:upnp-org:serviceId:SwitchPower1", action:"SetTarget", params:"{ \"newTargetValue\":0}"}},
	{r:"(exécuter|exécute|lance|lancer).*\\s+(%name%)", t:"scene" },
	{r:"(montre|montrer|ouvre|ouvrir).*\\s+(%name%)", t:"altui" },
	{r:"(montre|montrer|ouvre|ouvrir).*\\s+(%name%)", t:"room" }
]);
