//# sourceURL=J_ALTUI_loc_es.js
// http://192.168.1.16:3480/data_request?id=lr_ALTUI_Handler&command=home&lang=es
// This program is free software: you can redistribute it and/or modify
// it under the condition that it is for private or home useage and 
// this whole comment is reproduced in the source code file.
// Commercial utilisation is not authorized without the appropriate
// written agreement from amg0 / alexis . mermet @ gmail . com
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 

Localization.init( {
	"Home": "Casa",
	"Away":"Fuera",
	"Night":"Noche",
	"Vacation":"Vacaciones",
	"Room": "Habitacion",
	"Rooms": "Habitaciones",
	"Device":"Dispositivo",
	"Devices": "Dispositivos",
	"Control Panel": "Panel de Control",
	"Scenes": "Escena",
	"Scene Edit": "Editar Escena",
	"Plugins": "Plugins",
	"Custom Pages": "Paginas Personalizadas",
	"Edit Pages": "Modifica Paginas",
	"Credits": "Creditos",
	"LuaTest": "LuaPrueba",
	"LuaStart": "LuaInicio",
	"Optimize": "Optimiza",
	"Editor": "Editor",
	"Close":"Cerrar",
	"Custom Pages Editor": "Editor de Paginas Personalizadas",
	"Lua Startup": "Lua Arranque",
	"Lua Code Test":"Lua Prueba de Codigo",
	"Options": "Opciones",
	"Unmuted,Muted":"Normal,Mudo",
	"Normal,Debug":"Normal,Debug",
	"Up":"Subir",
	"Stop":"Parar",
	"Down":"Bajar",
	"Open":"Abrir",
	"Unlock,Lock":"Desbloquear,Bloquear",
	"Bypass,Arm":"Bypass,Armado",
	"Use Custom Pages":"Usar Paginas Personalizadas",
	"Edit Custom Pages":"Modificar Paginas Personalizadas",
	"More":"Mas",
	"Less":"Menos",
	"Remote Access Login":"Login de Accesso Remoto",
	"Reload Luup Engine":"Actualizar Motor Luup",
	"Lua Startup Code":"Lua Inicio de Codigo",
	"Lua Test Code":"Lua Prueba de Codigo",
	"Localization":"Localizacion",
	"Misc":"Varios",
	"Create":"Crear",
	"Runs in all modes, or in selected mode": "Ejecutar en todos los modos, o en el modo seleccionado",
	"Run" : "Ejecutar",
	"OFF,ON":"Apagado,Prendido",
	"Working":"Trabajando",
	"Holiday":"Feriado",
	"Wind":"Viento",
	"Are you sure you want to delete scene ({0})":"Esta seguro que desea borrar la escena ({0})",
	"Controller {0} is busy, be patient.":"Controlador {0} esta ocupado, sea paciente.",
	"Submit":"Enviar",
	"Save Changes":"Guardar Cambios",
	"Notification":"Notificacion",
	"Triggers":"Disparadores",
	"Timers":"Temporizadores",
	"Actions":"Acciones",
	"Lua":"Lua",
	"OffLabel":"EtiquetaApagado",
	"OnLabel":"EtiquetaPrendido",
	"Label":"Etiqueta",
	"Min":"Min",
	"Green":"Verde",
	"Orange":"Naranja",
	"Red":"Rejo",
	"Max":"Max",
	"Ticks":"Marcas",
	"TimerName":"TemporizadorNombre",
	"TimerType":"TemporizadorTipo",
	"TimerInterval":"TemporizadorIntervalo",
	"TimerDayOfWeek":"TemporizadorDiaDeSemana",
	"TimerDayOfMonth":"TemporizadorDiaDeMes",
	"TriggerName":"DisparadorNombre",
	"Delay":"Demora",
	"Action to switch OFF":"Accion para Apagar Interruptor",
	"Action to switch ON":"Accion para Prender Interruptor",
	"Action":"Accion",
	"Device Variable Properties":"Propiedades Variables de Dispositivo",
	"Parameters":"Parametros",
	"Value":"Valor",
	"Variable":"Variable",
	"Attributes":"Atributos",
	"Load":"Carga",
	"Info":"Info",
	"Image":"Imagen",
	"Run Scene":"Ejecutar Escena",
	"Edit":"Editar",
	"Camera":"Camara",
	"On Off":"Prendido Apagado",
	"Gauge":"Medir",
	"Device Icon":"Icono de Dispositivo",
	"Scene":"Escena",
	"Multi State":"Multi Estado",
	"Mo":"Lu",
	"Tu":"Ma",
	"We":"Mi",
	"Th":"Ju",
	"Fr":"Vi",
	"Sa":"Sa",
	"Su":"Do",
	"At a certain time of day":"A una determinada hora del dia",
	"At sunrise":"Al amanecer",
	"Before sunrise":"Antes del amanecer",
	"After sunrise":"Despues del amanecer",
	"At sunset":"A la puesta del sol",
	"Before sunset":"Antes de la puesta del sol",
	"After sunset":"Despues de la puesta del sol",
	"Timer":"Temporizador",
	"**Illegal**":"**Ilegal**",
	"interval":"intervalo",
	"day of week":"dia de la semana",
	"day of month":"dia del mes",
	"absolute":"absoluto",
	"Search":"Busqueda",
	"Remove":"Eliminar",
	"No Match":"No hay coincidencia",
	"Reboot Vera":"Reiniciar Vera",
	"This plugin is a work in progress, it will continuously evolve over time.":"Este plugin es un trabajo en curso, evolucionara contiuamente a traves del tiempo.",
	"You may check out the evolutions on the Micasaverde <a href='http://forum.micasaverde.com/index.php/topic,30310.msg216129.html#msg216129'>Forum</a>":"Usted puede ver la evolucion en Micasaverde <a href='http://forum.micasaverde.com/index.php/topic,30310.msg216129.html#msg216129'>Forum</a>",
	"All":"Todos",
	"No Room":"Sin habitacion",
	"Device creation failed":"Fallo en la creacion de dispositivo",
	"Device {0} created successfully":"Dispositivo {0} creado exitosamente",
	"Filter":"Filtro",
	"Category":"Categoria",
    "Could not create Room":"No pudo crear Habitacion",
	"New Page":"Nueva Pagina",
	"Page Properties":"Propiedades de la Pagina",
	"Delete this Page":"Borrar esta Pagina",
	"Save All Pages":"Guardar Todas las Paginas",
	"Files":"Archivos",
	"Name":"Nombre",
	"Version":"Version",
	"Update":"Actualizar",
	"Uninstall":"Desinstalar",
	"Messages":"Mensajes",
	"zWave Network":"Red zWave",
	"ZWave":"ZWave",
	"Localize":"Localizar",
	"Localizations":"Localizaciones",
	"Power Chart":"Cuadro de Energia",
	"Power":"Energia",
	"Localization information":"Informacion de Localizacion",
	"Mesh":"Malla",
	"Order By":"Ordenado por",
	"Reset Poll Counters":"Reiniciar Contadores del escrutinio",
	"Parent/Child Network":"Red Padre/Hijo","Parent/Child":"Padre/Hijo",
	"Drag and Drop to add/move/delete controls. use Ctrl+Click or lasso to select multiple controls":"Arrastre y suelte para agregar/mover/eliminar controles. Use Ctrl+Click o laso para seleccionar multiples controles",
	"Drag and Drop to fix the position of a node. Simple Click to open or collapse a parent node, Shift Click to free a fixed node":"Arrastre y suelte para agreglar la posicion de un nodo. Click simple para abrir o contraer un nodo padre, Shift Click para liberar un nodo fijo"	,
	"Network Quality":"Calidad de Red",
	"Quality":"Calidad",
	"Show":"Show",
	"ZWave Routes":"Rutas ZWave",
	"Scene Action Group":"EScena de Accion de Grupo",
  "Pause Scene":"Pausar Escena",
	"Trigger Restriction":"Restriccion de Disparador",
	"Restrict trigger based on certain times":"Restringir disparador basado en ciertos horarios",
	"Start Time":"Hora de Inicio",
	"Stop Time":"Hora de Fin",
	"zWave Routes":"Rutas zWave",
	"zWaveRoutes":"zWaveRutas",
	"error happened during decoding triggers, probable duplicate ID or invalid format":"error ocurrido durante decodificacion de disparadores, probable ID duplicado o formato invalido",
	"TblDevices":"TblDispositivos",
	"Table Devices":"Tabla Dispositivos",
	"Update Neighbors":"Actualizar Vecinos",
	"Update Neighbors succeeded":"Actualizacion exitosa de vecinos",
	"Copy to clipboard":"Copiar al portapapeles",
	"Data copied in clipboard":"Datos copiados en el portapapeles",
	"Code execution succeeded":"Ejecucion exitosa de codigo",
	"Code execution failed":"Ejecucion fallida de codigo",
	"Reboot request succeeded":"Requerimiento de reinicio exitoso",
	"Reboot request failed":"Requerimiento de reinicio fallido",
	"Favorite":"Favorito",
	"Favorites":"Favoritos",
	"Variables":"Variables",
	"Used in":"Usado en",
	"OsCommand":"ComandoSO",
	"Disk Usage":"Uso de Disco",
	"Free Space":"Espacio Libre",
	"Plugin Files":"Archivos Plugin",
	"Log Sizes":"Tamaños de Bitacora",
	"OS Command":"Comando SO",
	"Frequent Commands":"Comandos Frecuentes",
	"Output":"Salida",
	"Os Command execution succeeded":"Ejecucion exitosa de Comando SO",
	"Version number or empty for latest official version":"Numero de Version o vacio para la ultima version oficial",
	"Update Plugin succeeded, be patient Luup will reload":"Actualizacion exitosa del plugin, sea paciente Luup se reiniciara",
	"Enter a Vera OS ( Unix ) command, the stdout will be returned and displayed below":"Ingrese un comando Vera OS ( Unix ), la salida estandar será mostrada abajo",
	"Os Command execution on vera failed.":"Ejecucion del comando SO en Vera fallo.",
	"failed to execute":"falla de ejecucion",
	"Are you Sure ?":"Esta seguro ?",
	"Yes":"Si",
	"Are you sure you want to delete device ({0})":"Esta seguro que desea eliminar el dispositivo ({0})",
	"Are you sure you want to delete room":"Esta seguro que desea eliminar la habitacion",
	"Are you sure you want to uninstall this plugin #{0} and all its created devices":"Esta seguro que desea desinstalar este plugin #{0} y todos sus dispositivos creados",
	"a newer version #{0} of ALTUI is available, do you want to upgrade ?":"una nueva version #{0} de ALTUI esta disponible, desea actualizarla ?",
	"Question":"Pregunta",
	"Options":"Opciones",
	"Show Video Thumbnail in Local mode":"Mostrar miniatura de Video en modo Local",
	"Cache Control":"Control de Cache",
	"Custom Pages Control":"Control de Paginas Personalizadas",
	"Refresh":"Refrecar",
	"Search Logs":"Bitacoras de Busqueda",
	"Tail Logs":"Bitacoras de Cola",
	"label":"etiqueta",
	"command":"comando",
	"Add":"Agregar",
	"Default":"Defecto",
	"Command Parameters":"Parametros de Comando",
	"Parameter":"Parametro",
	"Test Code":"Prueba de Codigo",
	"Panels":"Paneles",
	"Reports":"Reportes",
	"Evolutions":"Evoluciones",
	"History":"Historia",
	"Date":"Fecha","Old":"Antiguo","New":"Nuevo",
	"Scene History":"Historia de Escena",
	"Button Label":"Etiqueta de Boton","Color":"Color",
	"Ran Scene #{0} successfully":"Escena #{0} ejecutada exitosamente",
	"Not used in scenes":"No usadoen escenas",
	"Controller {0} did not respond":"Controlador {0} no respondio",
	"Option":"Opcion",
	"Debug":"Depuracion",
	"All devices":"Todos los dispositivos",
	"One Device's States":"Estados de un Dispositivo",
	"Variable search":"Busqueda de variable",
	"Javascript code":"Codigo Javascript",
	"Debug Tools":"Herramientas de Depuracion",
	"Debug Actions":"Acciones de Depuracion",
	"Altui ID":"ID de Altui",
	"Variable Name Pattern":"Patron de Nombre de Variable",
	"an error happened during the execution":"ocurrio un error durante la ejecucion",
	"Controller":"Controlador",
	"Counters have been reset properly":"Los contadores han sido reiniciados apropiadamente",
	"do you want to change Lua startup code ? if yes, it will generate a Lua reload, be patient...":"desea cambiar los codigos de inicio Lua  ? si es asi, se generara una recarga Lua, sea paciente...",
	"Lua Startup code has been modified":"El codigo de inicio Lua ha sido modificadoooooo",
	"Header":"Cabecera",
	"Delay":"Demora",
	"Edited Scene {0} successfully":"Escena {0} editada exitosamente",
	"Notification from {0}":"Notificaciones desde {0}",
	"Notify Users":"Notificar Usuarios",
	"Deleted Scene {0} successfully":"Escena {0} eliminada exitosamente",
	"Left Buttons are fixed on the page":"Botones izquierdos son fijos en la pagina",
	"See":"Ver",
	"2-columns Menu's limit":"limite de menu de 2-columnas",
	"Find Json":"Encontrar Json",
	"Frame":"Marco",
	"Reload is done":"Reinicio listo",
	"Device Triggers":"Disparadores de Dispositivo",
	"Trigger":"Disparador",
	"Device Variable Watches":"Vigilancias de Variable de Dispositivo",
	"Watch":"Vigilar",
	"Lua Expression with new=newvalue and old=oldvalue":"Expresion Lua con nuevo=nuevovalor y antiguo=valorantiguo",
	"Expression with old new as variables and lua operators like <  >  <= >= == ~=":"Expresion con antiguo nuevo como variables y operadores lua como <   >   <=  >=  ==  ~=",
	"Logs":"Bitacoras",
	"Play":"Ejecutar",
	"Night,Day":"Noche,Dia",
	"Show Weather on home page":"Mostrar Clima en pagina de inicio",
	"Weather Temp Unit (UI5)":"Unidad de Tiempo de Clima (UI5)",
	"Watch Formula":"Formula Vigilada","Generated code":"Codigo Generado",
	"Edit Watch Expression":"Editar Expresion Vigilada",
	"Return Result":"Resultado devuelto",
	"Console Output":"Salida de Consola",
	"Lua execution succeeded":"Ejecucion exitosa de Lua",
	"This test code will succeed if it is syntactically correct. It must be the body of a function and can return something. The return object and console output will be displayed)":"Este codigo de prueba sera exitoso si esta sintacticamente correcto. Debe ser el cuerpo de una funcion y pueden retornar algo. El objeto retornado y la salida de la consola seran mostrados)",
	"H M S part of a timestamp":"H M S parte de una hora",
	"H M S duration in seconds":"H M S duracion en segundos",
	"Convert text to number":"Convertir texto a numero",
	"Welcome to ALTUI":"Bienvenido a la IU Aternativa de VERA",
	"Use Vera Favorites":"Use Favoritos Vera",
	"Graph":"Grafico",
	"Themes":"Temas",
	"Arm":"Armar",
	"Bypass":"Bypass",
	"Restart":"Reiniciar",
	"On":"Prendido","Off":"Apagado","Reset":"Reiniciar",
	"Create Device succeeded":"Creacion exitosa de Dispositivo",
	"Configuration":"Configuracion",
	"Deleted Device {0} successfully":"Eliminacion exitosa del Dispositivo {0}",
	"Reset Theme Override":"Restablecer el cambio de Tema",
	"Preview":"Vista previa",
	"Delete":"Eliminar",
	"Settings":"Ajustes",
	"Controllers":"Controllers",
	"Support":"Support",
	"TblScenes":"TblScenes",
	"TblControllers":"TblControllers",
	"TblWatches":"TblWatches",
	"Save":"Save",
	"Frame Properties":"Frame Properties",
	"Frame Label":"Frame Label",
	"background CSS":"background CSS",
	"IFrame Url":"IFrame Url",
	"Optional, if specified frame will be filled in with this url":"Optional, if specified frame will be filled in with this url",
	"Same Room for Devices/Scenes":"Same Room for Devices/Scenes",
	"Rules":"Rules",
	"Timeline":"Timeline",
	"Table Scenes":"Table Scenes",
	"Use new UI7 behavior for Heater devices":"Use new UI7 behavior for Heater devices",
	"Show all rows in grid tables":"Show all rows in grid tables",
	"Table Controllers":"Table Controllers"	,
	"Unregistered version for {0}":"Unregistered version for {0}",
	"Registered Version":"Registered Version",
	"Hide":"Hide",
	"Value ON":"Value ON",
	"Value OFF":"Value OFF",
	"Push to {5}":"Push to {5}",
	"Table Watches":"Table Watches",
	"Are you sure you want to delete scene watch ({0})":"Are you sure you want to delete scene watch ({0})",
	"Are you sure you want to delete data push ({0})":"Are you sure you want to delete data push ({0})",
	"Watch Display":"Watch Display","WatchDisplay":"WatchDisplay",
	"Alert - Camera":"Alert - Camera",
	"Workflows":"Workflows",
	"Workflow Pages":"Workflow Pages",
	"Workflow":"Workflow",
	"Test":"Test",
	"Workflow Editor":"Workflow Editor",
	"State":"State",
	"State Properties":"State Properties",
	"State Name":"State Name",
	"State Actions":"State Actions",
	"On Enter":"On Enter",
	"On Exit":"On Exit",
	"Link Properties":"Link Properties",
	"Link Name":"Link Name",
	"Link Conditions":"Link Conditions",
	"Conditions":"Conditions",
	"All conditions must match ( logical AND ) for the transition to happen":"All conditions must match ( logical AND ) for the transition to happen",
	"Timer Name":"Timer Name",
	"Duration":"Duration",
	"Distribute Horizontally":"Distribute Horizontally",
	"Distribute Vertically":"Distribute Vertically",
	"Slider":"Slider",
	"Workflow Report":"Workflow Report",
	"Upgrade Request succeeded, a Luup reload will happen":"Upgrade Request succeeded, a Luup reload will happen",
	"Invisible":"Invisible",
	"Battery":"Battery",
	"Zigbee":"Zigbee",
	"Bluetooth":"Bluetooth",
	"Pause Workflow":"Pause Workflow",
	"Report":"Report",
	"Copy":"Copy",
	"In Local access mode, show camera in video stream mode":"In Local access mode, show camera in video stream mode",
	"ShowVideoThumbnail:In Local access mode, show camera in video stream mode":"ShowVideoThumbnail:In Local access mode, show camera in video stream mode",
	"choose whether or not the selection Buttons on the left are scrolling with the page":"choose whether or not the selection Buttons on the left are scrolling with the page",
	"FixedLeftButtonBar:choose whether or not the selection Buttons on the left are scrolling with the page":"FixedLeftButtonBar:choose whether or not the selection Buttons on the left are scrolling with the page",
	"display or not the weather widget on home page":"display or not the weather widget on home page",
	"ShowWeather:display or not the weather widget on home page":"ShowWeather:display or not the weather widget on home page",
	"use the same favorites as set on your VERA box but prevent to have different favorites per client device":"use the same favorites as set on your VERA box but prevent to have different favorites per client device",
	"UseVeraFavorites:use the same favorites as set on your VERA box but prevent to have different favorites per client device":"UseVeraFavorites:use the same favorites as set on your VERA box but prevent to have different favorites per client device",
	"keep the same last selected room between the device and the scene pages":"keep the same last selected room between the device and the scene pages",
	"SyncLastRoom:keep the same last selected room between the device and the scene pages":"SyncLastRoom:keep the same last selected room between the device and the scene pages",
	"Fixes the footer at the bottom of the page but could have performance issues on mobile browsers":"Fixes the footer at the bottom of the page but could have performance issues on mobile browsers",
	"Sticky Footer to bottom":"Sticky Footer to bottom",
	"StickyFooter:Fixes the footer at the bottom of the page but could have performance issues on mobile browsers":"StickyFooter:Fixes the footer at the bottom of the page but could have performance issues on mobile browsers",
	"technical option to trigger the UI7 behavior for heater":"technical option to trigger the UI7 behavior for heater",
	"UseUI7Heater:technical option to trigger the UI7 behavior for heater":"UseUI7Heater:technical option to trigger the UI7 behavior for heater",
	"allways show all the lines in the grid tables, or have a row count selector instead":"allways show all the lines in the grid tables, or have a row count selector instead",
	"ShowAllRows:allways show all the lines in the grid tables, or have a row count selector instead":"ShowAllRows:allways show all the lines in the grid tables, or have a row count selector instead",
	"if a menu has more entries than this number then show the menu entries in 2 columns":"if a menu has more entries than this number then show the menu entries in 2 columns",
	"Menu2ColumnLimit:if a menu has more entries than this number then show the menu entries in 2 columns":"Menu2ColumnLimit:if a menu has more entries than this number then show the menu entries in 2 columns",
	"Unit for temperature":"Unit for temperature",
	"TempUnitOverride:Unit for temperature":"TempUnitOverride:Unit for temperature",
	"Editor Control":"Editor Control",
	"Editor Theme":"Editor Theme",
	"Editor font size in pixels":"Editor font size in pixels",
	"Editor Font Size":"Editor Font Size",
	"EditorFontSize:Editor font size in pixels":"EditorFontSize:Editor font size in pixels",
	"info":"info",
	"Bag":"Bag",
	"Import/Export":"Import/Export",
	"Variables Bag":"Variables Bag",
	"No data to display":"No data to display",
	"Schedules":"Schedules",
	"Duration (sec)":"Duration (sec)",
	"None":"None",
	"Only in the following mode(s)":"Only in the following mode(s)",
	"Record":"Record",
	"Normal,Recorder":"Normal,Recorder",
	"Are you sure you want to modify this attribute":"Are you sure you want to modify this attribute",
	"License Fees":"License Fees",
	"License":"License",
	"Horizontal Slider":"Horizontal Slider",
	"For non commercial use, ALTUI plugin is free for trial without limitation on its functionality. However, to compensate the effort and time spent on regularly improving this project, a registration fee equivalent to <span class='text-info'><mark><b>2€ per month</b></mark></span> is requested for longer term use. You can choose your level of contribution.":"For non commercial use, ALTUI plugin is free for trial without limitation on its functionality. However, to compensate the effort and time spent on regularly improving this project, a registration fee is requested for longer term use. You can choose your level of contribution.",
	"Once registered you will get:<ul><li>Access to all the releases and auto update mechanism (not available to non registered users)</li><li>Removal of unregistered welcome message, as well as license message in the footer</li></ul>":"Once registered you will get:<ul><li>Access to all the releases and auto update mechanism (not available to non registered users)</li><li>Removal of unregistered welcome message, as well as license message in the footer</li></ul>",
	"Resellers or Integrators are welcome to contact me for eventual commercial agreements.":"Resellers or Integrators are welcome to contact me for eventual commercial agreements.",
	"Check for Updates":"Check for Updates",
	"Unregistered Version":"Unregistered Version",
	"active":"active",
	"Device zWave Parameters":"Paramètres module zWave",
	"Lua Editor":"Éditeur Lua",
	"Recording...":"Enregistrement...",
	"Close for 24h":"Fermer pour 24h",
	"Backup Controller":"Backup Controller",
	"ZWave Heal":"ZWave Heal",
	"ZWave Inclusion":"ZWave Inclusion",
	"ZWave Exclusion":"ZWave Exclusion",
	"Details":"Details",
	"You already have the latest version":"You already have the latest version",
	"Prevent drag and drop of favorites to reorder them":"Prevent drag and drop of favorites to reorder them",
	"Lock favorites position":"Lock favorites position",
	"LockFavoritePosition:Prevent drag and drop of favorites to reorder them":"LockFavoritePosition:Prevent drag and drop of favorites to reorder them",
	"Top":"Top","Page Up":"Page Up","Page Down":"Page Down","Bottom":"Bottom",
	"App Store":"App Store","Publish App":"Publish App","Install":"Install","Application Store":"Application Store",
	"Publish":"Publish","ALT":"ALT","Vera":"Vera","Publish Application":"Publish Application",
	"Contacting Server...":"Contacting Server...",
	"Please go to this page <a href='{1}' target='_blank'>{1}</a> and enter this code : {0}":"Please go to this page <a href='{1}' target='_blank'>{1}</a> and enter this code : {0}",
	"Select an App":"Select an App","Publish an App":"Publish an App",
	"Application":"Application","App ID":"App ID","App Title":"App Title",
	"VersionMajor":"VersionMajor","VersionMinor":"VersionMinor","Description":"Description",
	"Icon":"Icon","DeviceFileName":"DeviceFileName","DeviceType":"DeviceType","ImplFile":"ImplFile",
	"GitHub":"GitHub","backup":"backup","default":"default","downloads":"downloads",
	"pattern":"pattern","source":"source","Vera Store":"Vera Store","version":"version","Modify":"Modify"

});

// override rules with localized version
SpeechManager.initRules([
	{r:"(switch on|turn on|open).*\\s+(%name%)", t:"device", a:{service:"urn:upnp-org:serviceId:SwitchPower1", action:"SetTarget", params:"{ \"newTargetValue\":1}"}},
	{r:"(switch off|turn off|close).*\\s+(%name%)", t:"device", a:{service:"urn:upnp-org:serviceId:SwitchPower1", action:"SetTarget", params:"{ \"newTargetValue\":0}"}},
	{r:"(run|launch).*\\s+(%name%)", t:"scene" },
	{r:"(show|open).*\\s+(%name%)", t:"altui" },
	{r:"(show|open).*\\s+(%name%)", t:"room" }
]);	
		
