//# sourceURL=J_ALTUI_loc_nl.js
// http://192.168.1.16:3480/data_request?id=lr_ALTUI_Handler&command=home
// This program is free software: you can redistribute it and/or modify
// it under the condition that it is for private or home useage and 
// this whole comment is reproduced in the source code file.
// Commercial utilisation is not authorized without the appropriate
// written agreement from amg0 / alexis . mermet @ gmail . com
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 

Localization.init( {
	"Home":"Thuis",
	"Away":"Afwezig",
	"Night":"Nacht",
	"Vacation":"Vakantie",
	"Room": "Kamer",
	"Rooms": "Kamers",
	"Device": "Apparaat",
	"Devices": "Apparaten",
	"Control Panel": "Controle paneel",
	"Scenes": "Scènes",
	"Scene Edit": "Bewerk Scène",
	"Plugins": "Plugins",
	"Custom Pages": "Custom pagina’s",
	"Edit Pages": "Bewerk pagina’s",
	"Credits": "Credits",
	"LuaTest": "LuaTest",
	"LuaStart": "LuaStart",
	"Optimize": "Optimaliseer",
	"Editor": "Editor",
	"Close": "Sluit",
	"Custom Pages Editor": "Custom pagina’s Editor",
	"Lua Startup": "Startup Lua",
	"Lua Code Test":"Test Lua code",
	"Options": "Opties",
	"Unmuted,Muted":"Normaal,Gedempt",
	"Normal,Debug":"Normaal,Debug",
	"Up":"Omhoog",
	"Stop":"Stop",
	"Down":"Omlaag",
	"Open":"Open",
	"Unlock,Lock":"Ontsluit,Sluit",
	"Bypass,Arm":"Deactiveer,Activeer",
	"Use Custom Pages":"Gebruik Custom pagina’s",
	"Edit Custom Pages":"Custom pagina’s bewerken",
	"More":"Meer",
	"Less":"Minder",
	"Remote Access Login":"Remote Access Login",
	"Reload Luup Engine":"Herstart Luup Engine",
	"Lua Startup Code":"Lua Opstart code",
	"Lua Test Code":"Lua Test Code",
	"Localization":"Lokalisatie",
	"Misc":"Diverse",
	"Create":"Creër",
	"Runs in all modes, or in selected mode": "Run in alle modes, of in geselecteerde mode",
	"Run":"Run",
	"OFF,ON":"UIT,AAN",
	"Working":"Bezig",
	"Holiday":"Vakantie",
	"Wind":"Wind",
	"Are you sure you want to delete scene ({0})":"Wilt u scène {0} verwijderen?",
	"Controller {0} is busy, be patient.":"De Controller {0} is bezig, even geduld ...",
	"Submit":"Verstuur",
	"Save Changes":"Veranderingen opslaan",
	"Notification":"Notificatie",
	"Triggers":"Triggers",
	"Timers":"Timers",
	"Actions":"Acties",
	"Lua":"Lua",
	"OffLabel":"Uit label",
	"OnLabel":"Aan label",
	"Label":"Label",
	"Min":"Min",
	"Green":"Groen",
	"Orange":"Orange",
	"Red":"Rood",
	"Max":"Max",
	"Ticks":"Tikken",
	"TimerName":"Timernaam",
	"TimerType":"Timertype",
	"TimerInterval":"Timerinterval",
	"TimerDayOfWeek":"Timer Dag van de week",
	"TimerDayOfMonth":"Timer Dag van de maand",
	"TriggerName":"Triggernaam",
	"Delay":"Vertraging",
	"Action to switch OFF":"Actie om schakelaar UIT te zetten",
	"Action to switch ON":"Actie om schakelaar AAN te zetten",
	"Action":"Actie",
	"Device Variable Properties":"Apparaat variabele eigenschappen",
	"Parameters":"Parameters",
	"Value":"Waarde",
	"Variable":"Variabele",
	"Attributes":"Attributen",
	"Load":"Laden",
	"Info":"Info",
	"Image":"Afbeelding",
	"Run Scene":"Start Scène",
	"Edit":"Bewerk",
	"Camera":"Camera",
	"On Off":"Aan Uit",
	"Gauge":"Meter",
	"Device Icon":"Apparaat icoon",
	"Scene":"Scène",
	"Multi State":"Multi Status",
	"Mo":"Ma",
	"Tu":"Di",
	"We":"Wo",
	"Th":"Do",
	"Fr":"Vr",
	"Sa":"Za",
	"Su":"Zo",
	"At a certain time of day":"Op een bepaald moment van de dag",
	"At sunrise":"Bij zonsopkomst",
	"Before sunrise":"Voor zonsopkomst",
	"After sunrise":"Na zonsopkomst",
	"At sunset":"Bij zonsondergang",
	"Before sunset":"Voor zonsondergang",
	"After sunset":"Na zonsondergang",
	"Timer":"Timer",
	"**Illegal**":"**Illegaal**",
	"interval":"interval",
	"day of week":"dag van de week",
	"day of month":"dag van de maand",
	"absolute":"Vast tijdstip",
	"Search":"Zoek",
	"Remove":"Verwijder",
	"No Match":"Niet gevonden",
	"Reboot Vera":"Herstart Vera",
	"This plugin is a work in progress, it will continuously evolve over time.":"Deze Plugin is onder ontwikkeling, het zal beter worden.",
	"You may check out the evolutions on the Micasaverde <a href='http://forum.micasaverde.com/index.php/topic,30310.msg216129.html#msg216129'>Forum</a>":"Je kunt kijken op het Micasaverde <a href='http://forum.micasaverde.com/index.php/topic,30310.msg216129.html#msg216129'>Forum</a> ",
	"All":"Alle",
	"No Room":"Geen kamer",
	"Device creation failed":"Apparaat creatie mislukt",
	"Device {0} created successfully":"Apparaat {0} succesvol aangemaakt",
	"Filter":"Filter",
	"Category":"Categorie",
	"Could not create Room":"Kan de kamer niet aanmaken",
	"New Page":"Nieuwe pagina",
	"Page Properties":"Pagina eigenschappen",
	"Delete this Page":"Verwijder deze pagina",
	"Save All Pages":"Sla alle pagina’s op",
	"Files":"Bestanden",
	"Name":"Naam",
	"Version":"Versie",
	"Update":"Bijwerken",
	"Uninstall":"Deinstalleren",
	"Messages":"Berichten",
	"zWave Network":"zWave netwerk",
	"ZWave":"ZWave",
	"Localize":"Lokaliseer",
	"Localizations":"Lokalisaties",
	"Power Chart":"Vermogensgrafiek",
	"Power":"Engergieverbruik",
	"Localization information":"Lokalisatie informatie",
	"Mesh":"Netwerk",
	"Order By":"Sorteer op",
	"Reset Poll Counters":"Reset tellers",
	"Parent/Child Network":"Parent/Child netwerk",
	"Parent/Child":"Parent/Child",
	"Drag and Drop to add/move/delete controls. use Ctrl+Click or lasso to select multiple controls":"Drag and Drop om controls verwijderen/verplaatsen/toe te voegen. Gebruik Ctrl+Click of lasso om meerdere te selecteren",
	"Drag and Drop to fix the position of a node. Simple Click to open or collapse a parent node, Shift Click to free a fixed node":"Drag and Drop om de positie van een node te fixeren. Klik om een parent node te openen of sluiten",
	"Network Quality":"Netwerkkwaliteit",
	"Quality":"Kwaliteit",
	"Show":"Toon",
	"zWave Routes":"zWave Routes",
	"Scene Action Group":"Scène actie groep",
	"Pause Scene":"Pauseer Scène",
	"Trigger Restriction":"Trigger beperking",
	"Restrict trigger based on certain times":"Beperk trigger op basis van tijden",
	"Start Time":"Starttijd",
	"Stop Time":"Eindtijd",
	"zWave Routes":"zWave Routes",
	"zWaveRoutes":"zWaveRoutes",
	"error happened during decoding triggers, probable duplicate ID or invalid format":"er is een fout opgetreden tijdens het decoderen van triggers, waarschijnlijk door een duplicaat ID of foutief formaat",
	"TblDevices":"TblDevices",
	"Table Devices":"Apparaat tabel",
	"Update Neighbors":"Buren bijwerken",
	"Update Neighbors succeeded":"buren bijwerken gelukt",
	"Copy to clipboard":"Kopieer gegevens naar het klembord",
	"Data copied in clipboard":"Gegevens gekopieerd naar het klembord",
	"Code execution succeeded":"Code succesvol uitgevoerd",
	"Code execution failed":"Code uitvoer mislukt",
	"Reboot request succeeded":"Herstart verzoek gelukt",
	"Reboot request failed":"Herstart verzoek mislukt",
	"Favorite":"Favoriet",
	"Favorites":"Favorieten",
	"Variables":"Variabelen",
	"Used in":"Gebruikt in",
	"OsCommand":"OsCommando",
	"Disk Usage":"Disk gebruik",
	"Free Space":"Beschikbare ruimte",
	"Plugin Files":"Plugin bestanden",
	"Log Sizes":"Loggrootte",
	"OS Command":"OS Commando",
	"Frequent Commands":"Frequente commando's",
	"Output":"Uitvoer",
	"Os Command execution succeeded":"OS commando succesvol uitgevoerd",
	"Version number or empty for latest official version":"Versienummer of leeg voor recentste officiele versie",
	"Update Plugin succeeded, be patient Luup will reload":"Plugin bijwerken gelukt, even geduld voor een LUUP hestart",
	"Enter a Vera OS ( Unix ) command, the stdout will be returned and displayed below":"Type een Vera OS commando. De stdout wordt hieronder getoond",
	"Os Command execution on vera failed.":"OS Commando uitvoer op de Vera is mislukt",
	"failed to execute":"uitvoeren is mislukt",
	"Are you Sure ?":"Weet je het zeker ?",
	"Yes":"Ja",
	"Are you sure you want to delete device ({0})":"Weet je zeker dat je dit apparaat wil verwijderen ({0})",
	"Are you sure you want to delete room":"Weet je zeker dat je de kamer wilt verwijderen",
	"Are you sure you want to uninstall this plugin #{0} and all its created devices":"Weet je zeker dat je plugin #{0} en al zijn apparaten wilt verwijderen",
	"a newer version #{0} of ALTUI is available, do you want to upgrade ?":"Een nieuwere verzie #{0} van ALTUI is beschikbaar, wil je upgraden ?",
	"Question":"Vraag",
	"Options":"Opties",
	"Show Video Thumbnail in Local mode":"Toon video icoon in Lokale modus",
	"Cache Control":"Cache instellingen",
	"Custom Pages Control":"Custom pagina’s controle",
	"Refresh":"Ververs",
	"Search Logs":"Doorzoek Logs",
	"Tail Logs":"Tail Logs",
	"label":"label",
	"command":"commando",
	"Add":"Toevoegen",
	"Default":"Default",
	"Command Parameters":"Commando parameters",
	"Parameter":"Parameter",
	"Test Code":"Test Code",
	"Panels":"Panelen",
	"Reports":"Rapporten",
	"Evolutions":"Versie historie",
	"History":"Historie",
	"Date":"Datum",
	"Old":"Oud",
	"New":"Nieuw",
	"Scene History":"Scène historie",
	"Button Label":"Knoplabel",
	"Color":"Kleur",
	"Ran Scene #{0} successfully":"Scène #{0} succesvol uitgevoerd",
	"Not used in scenes or workflows":"Scène wordt niet gebruikt in workflows",
	"Controller {0} did not respond":"Controller {0} reageert niet",
	"Option":"Optie",
	"Debug":"Debug",
	"All devices":"Alle apparaten",
	"One Device's States":"Een apparaat status",
	"Variable search":"Zoek variabele",
	"Javascript code":"Javascript Code",
	"Debug Tools":"Debug gereedschap",
	"Debug Actions":"Debug acties",
	"Altui ID":"Altui ID",
	"Variable Name Pattern":"Variabele naam patroon",
	"an error happened during the execution":"er is een fout opgetreden tijdens de uitvoer",
	"Controller":"Controller",
	"Counters have been reset properly":"Tellers succesvol op nul gezet",
	"do you want to change lua startup code ? if yes, it will generate a Lua reload, be patient...":"wil je de LUA startup code aanpassen? Zoja dan genereerd dit een LUA herstart, even geduld...",
	"Lua Startup code has been modified":"De LUA startup code is aangepast",
	"Header":"Kop",
	"Delay":"Vertraging",
	"Edited Scene {0} successfully":"Scène {0} succesvol aangepast",
	"Notification from {0}":"Notificatie van {0}",
	"Notify Users":"Notificeer gebruikers",
	"Deleted Scene {0} successfully":"Scène {0} succesvol verwijderd",
	"Left Buttons are fixed on the page":"Linker knoppen staan vast op de pagina",
	"See":"Kijk",
	"2-columns Menu's limit":"2 kolom menu limiet",
	"Find Json":"Vind Json",
	"Frame":"Frame",
	"Reload is done":"Herladen compleet",
	"Device Triggers":"Apparaat triggers",
	"Trigger":"Trigger",
	"Device Variable Watches":"Apparaat variabelen monitors",
	"Watch":"Monitor",
	"Lua Expression with new=newvalue and old=oldvalue":"LUA uitdrukking met new=nieuwe waarde en old=oude waarde",
	"Expression with old new as variables and lua operators like <  >  <= >= == ~=":"Uitdrukking met old,new en lua operators als < > <= >= == ~=",
	"Logs":"Logs",
	"Play":"Speel af",
	"Night,Day":"Nacht,Dag",
	"Show Weather on home page":"Toon weer op start pagina",
	"Weather Temp Unit (UI5)":"Temperatuur eenheid (UI5)",
	"Watch Formula":"Monitor formule",
	"Generated code":"Gegenereerde code",
	"Edit Watch Expression":"Bewerk monitor uitdrukking",
	"Return Result":"Resultaat",
	"Console Output":"Console uitvoer",
	"Lua execution succeeded":"Lua uitvoer succesvol",
	"This test code will succeed if it is syntactically correct. It must be the body of a function and can return something. The return object and console output will be displayed)":"Deze test code zal slagen indien syntactisch juist. Het moet de kern van een functie zijn en kan een waarde retourneren. Het geretourneerde object en de console uitvoer wordt getoond.",
	"H M S part of a timestamp":"H M S deel van een timestamp",
	"H M S duration in seconds":"H M S duur in seconden",
	"Convert text to number":"Converteer tekst naar een nummer",
	"Welcome to ALTUI":"Welkom bij ALTUI",
	"Use Vera Favorites":"Gebruik de Vera favorieten",
	"Graph":"Diagram",
	"Themes":"Thema's",
	"Arm":"Activeer",
	"Bypass":"Deactiveer",
	"Restart":"Herstarten",
	"On":"Aan","Off":"Uit","Reset":"Reset",
	"Create Device succeeded":"Apparaat succesvol aangemaakt",
	"Configuration":"Configuratie",
	"Deleted Device {0} successfully":"Apparaat {0} succesvol verwijdert",
	"Reset Theme Override":"Reset thema",
	"Preview":"Voorvertoning",
	"Delete":"Verwijder",
	"Settings":"Instellingen",
	"Controllers":"Controllers",
	"Support":"Ondersteuning",
	"TblScenes":"Scènes tabel",
	"TblControllers":"Controllers tabel",
	"TblWatches":"Monitors tabel",
	"Save":"Opslaan",
	"Frame Properties":"Frame eigenschappen",
	"Frame Label":"Frame label",
	"Background CSS":"Achtergrond CSS",
	"IFrame Url":"IFrame Url",
	"Optional, if specified frame will be filled in with this url":"Optioneel, als opgegeven dan wordt het frame met deze URL gevuld",
	"Same Room for Devices/Scenes":"Zelfde kamer voor apparaten/scènes",
	"Rules":"Regels",
	"Timeline":"Tijdslijn",
	"Table Scenes":"Scènes Tabel",
	"Use new UI7 behavior for Heater devices":"Gebruik UI7 gedrag voor thermostaten",
	"Show all rows in grid tables":"Toon alle rijen in een rooster tabel",
	"Table Controllers":"Controllers tabel",
	"Unregistered version for {0}":"Ongeregistreerde versie van {0}",
	"Registered Version":"Geregistreerde versie",
	"Hide":"Verberg",
	"Value ON":"Waarde ON",
	"Value OFF":"Waarde OFF",
	"Watches":"Variabelen monitors",
	"Push to {5}":"Druk om {5}",
	"Table Watches":"Monitors tabel",
	"Are you sure you want to delete scene watch ({0})":"Weet je zeker dat je scène monitor ({0}) wilt verwijderen",
	"Are you sure you want to delete data push ({0})":"Weet je zeker dat je \"data push\" ({0}) wilt verwijderen",
	"Watch Display":"Monitor tabel",
	"WatchDisplay":"WatchDisplay",
	"Alert - Camera":"Alarm Camera",
	"Workflows":"Workflows",
	"Workflow Pages":"Workflows pagina's",
	"Workflow":"Workflow",
	"Test":"Test",
	"Workflow Editor":"Workflow editor",
	"State":"Status",
	"State Properties":"Status eigenschappen",
	"State Name":"Status naam",
	"State Actions":"Status acties",
	"On Enter":"Bij ingaan",
	"On Exit":"Bij verlaten",
	"Link Properties":"Link eigenschappen",
	"Link Name":"Link naam",
	"Link Conditions":"Link condities",
	"Conditions":"Condities",
	"All conditions must match ( logical AND ) for the transition to happen":"De overgang gebeurt als alle condities waar zijn (logische AND)",
	"Timer Name":"Timer naam",
	"Duration":"Duur",
	"Distribute Horizontally":"Verdeel horizontaal",
	"Distribute Vertically":"Verdeel verticaal",
	"Slider":"Schuif",
	"Workflow Report":"Workflow rapport",
	"Upgrade Request succeeded, a Luup reload will happen":"Upgrade verzoek succesvol, Luup zat herstarten",
	"Invisible":"Verborgen",
	"Battery":"Batterij",
	"Zigbee":"Zigbee",
	"Bluetooth":"Bluetooth",
	"Pause Workflow":"Pauzeer workflow",
	"Report":"Rapport",
	"Copy":"Copiër",
	"In Local access mode, show camera in video stream mode":"In lokale toegangsmode, toon de camera in video stream modus",
	"ShowVideoThumbnail:In Local access mode, show camera in video stream mode":"ShowVideoThumbnail:In lokale toegangsmode, toon de camera in video stream modus",
	"choose whether or not the selection Buttons on the left are scrolling with the page":"selecteer of de selectie knoppen links wel of niet mee scrollen met de pagina",
	"FixedLeftButtonBar:choose whether or not the selection Buttons on the left are scrolling with the page":"FixedLeftButtonBar:selecteer of de selectie knoppen links wel of niet mee scrollen met de pagina",
	"display or not the weather widget on home page":"toon het weer widget op de start pagina of niet",
	"ShowWeather:display or not the weather widget on home page":"ShowWeather:toon het weer widget op de start pagina of niet",
	"use the same favorites as set on your VERA box but prevent to have different favorites per client device":"gebruik dezelfde favorieten als op jou Vera, maar voorkom verschillende per cliënt",
	"UseVeraFavorites:use the same favorites as set on your VERA box but prevent to have different favorites per client device":"UseVeraFavorites:gebruik dezelfde favorieten al op jou Vera, maar voorkom verschillende per cliënt",
	"keep the same last selected room between the device and the scene pages":"gebruik de zelfde kamer selectie voor de apparaten en scènes pagina",
	"SyncLastRoom:keep the same last selected room between the device and the scene pages":"SyncLastRoom:gebruik de zelfde kamer selectie voor de apparaten en scènes pagina",
	"Fixes the footer at the bottom of the page but could have performance issues on mobile browsers":"Fixeer de footer onderaan de pagina. Dit kan de prestaties van mobile apparaten beïnvloeden",
	"Sticky Footer to bottom":"Fixeer de footer onderaan de pagina",
	"StickyFooter:Fixes the footer at the bottom of the page but could have performance issues on mobile browsers":"StickyFooter:Fixeer de footer onderaan de pagina. Dit kan de prestaties van mobile apparaten beïnvloeden",
	"technical option to trigger the UI7 behavior for heater":"technische mogelijkheid om UI7 gedrag voor thermostaten te triggeren",
	"UseUI7Heater:technical option to trigger the UI7 behavior for heater":"UseUI7Heater:technische mogelijkheid om UI7 gedrag voor thermostaten te triggeren",
	"allways show all the lines in the grid tables, or have a row count selector instead":"toon alle lijnen in een tabel rooster, of gebruik een rij teller selectie",
	"ShowAllRows:allways show all the lines in the grid tables, or have a row count selector instead":"ShowAllRows:toon alle lijnen in een tabel rooster, of gebruik een rij teller selectie",
	"if a menu has more entries than this number then show the menu entries in 2 columns":"indien een menu meer dan dit aantal items heeft, toon het menu dan in twee kolommen",
	"Menu2ColumnLimit:if a menu has more entries than this number then show the menu entries in 2 columns":"Menu2ColumnLimit:indien een menu meer dan dit aantal items heeft, toon het menu dan in twee kolommen",
	"Unit for temperature":"Temperatuur eenheid",
	"TempUnitOverride:Unit for temperature":"TempUnitOverride:Temperatuur eenheid",
	"Editor Control":"Editor Controle",
	"Editor Theme":"Editor thema",
	"Editor font size in pixels":"Editor lettertypegrootte in pixels",
	"Editor Font Size":"Editor lettertypegrootte in pixels",
	"EditorFontSize:Editor font size in pixels":"EditorFontSize:Editor lettertypegrootte in pixels",
	"info":"info",
	"Bag":"Mand",
	"Import/Export":"Import/Export",
	"Variables Bag":"Variabelen mand",
	"No data to display":"Geen data on te tonen",
	"Schedules":"Schema's",
	"Duration (sec)":"Duur (sec)",
	"None":"Geen",
	"Only in the following mode(s)":"Alleen in de volgende modus",
	"Record":"Opnemen",
	"Normal,Recorder":"Normaal,Recorder",
	"Are you sure you want to modify this attribute":"Weet je zeker dat je dit attribuut wilt veranderen",
	"License Fees":"Licentiekosten",
	"License":"Licentie",
	"Horizontal Slider":"Horizontale schuif",
	"For non commercial use, ALTUI plugin is free for trial with some limitation on its functionality. To compensate the effort and time spent on regularly improving this project, a registration fee equivalent to <span class='text-info'><mark><b>2€ per month</b></mark></span> is requested for longer term use. You can choose your level of contribution.":"Voor niet commercieel gebruik is de ALTUI plugin gratis om te proberen met alle functionaliteit. Ter compensatie voor alle tijd en moeite voor alle verbeteringen de registratiekosten van <span class='text-info'><mark><b>2€ per maand</b></mark></span> wordt verzocht bij langdurig gebruik. Je kan zelf de hoogte van je bijdrage bepalen",
	"Once registered you will get:<ul><li>Access to all the releases and auto update mechanism (not available to non registered users)</li><li>Removal of unregistered welcome message, as well as license message in the footer</li></ul>":"Zodra geregistreerd krijg je:<ul><li>Toegang tot alle nieuwe releases met auto update functionaliteit (niet beschikbaar voor niet geregistreerde gebruikers).</li><li>Niet langer het ongeregistreerd start bericht, alsook de melding onderaan de pagina's</li></ul>",
	"Resellers or Integrators are welcome to contact me for eventual commercial agreements.":"Wederverkopers en integrators kunnen contact met mij opnemen voor eventueel commercieel gebruik",
	"Check for Updates":"Controleer op updates",
	"Unregistered Version":"Ongeregistreerde versie",
	"active":"actief",
	"Device zWave Parameters":"Apparaat zWave parameters",
	"Lua Editor":"Lua Editor",
	"Recording...":"Recording...",
	"Close for 24h":"Sluit voor 24u",
	"Backup Controller":"Backup Controller",
	"ZWave Heal":"ZWave Heal",
	"ZWave Inclusion":"ZWave Inclusion",
	"ZWave Exclusion":"ZWave Exclusion",
	"Details":"Details",
	"You already have the latest version":"Je hebt al de meest recente versie",
	"Prevent drag and drop of favorites to reorder them":"Voorkom Drag en Drop van favorieten om te sorteren",
	"Lock favorites position":"Fixeer de favorieten positie",
	"LockFavoritePosition:Prevent drag and drop of favorites to reorder them":"LockFavoritePosition: Voorkom Drag en Drop van favorieten om te sorteren",
	"Top":"Top",
	"Page Up":"Pagina omhoog",
	"Page Down":"Pagina omlaag",
	"Bottom":"Onderkant",
	"App Store":"App Store","Publish App":"Publiceer Applicatie","Install":"Installeren","Application Store":"Applicatie Store",
	"Publish":"Publiceer","ALT":"ALT","Vera":"Vera","Publish Application":"Publiceer Applicatie",
	"Contacting Server...":"Verbinding maken met Server...",
	"Please go to this page <a href='{1}' target='_blank'>{1}</a> and enter this code : {0}":"Ga naar deze pagina <a href='{1}' target='_blank'>{1}</a> en type deze code : {0}",
	"Select an App":"Selecteer een Applicatie","Publish an App":"Publiceer een Applicatie",
	"Application":"Applicatie","App ID":"App ID","App Title":"Applicatie titel",
	"VersionMajor":"VersionMajor","VersionMinor":"VersionMinor","Description":"Beschrijving",
	"Icon":"Icoon","DeviceFileName":"DeviceFileName","DeviceType":"DeviceType","ImplFile":"ImplFile",
	"GitHub":"GitHub","backup":"backup","default":"default","downloads":"downloads",
	"pattern":"pattern","source":"source","Vera Store":"Vera Store","version":"versie","Modify":"Aanpassen",
	"Refreshing Token...":"Ververs Token...","Authenticating client device...":"Authenticatie van cliënt...",
	"Please go to this page <a href='{1}' target='_blank'>{1}</a> and enter this code : <mark>{0}</mark> <div class='altui-plugin-msg2'></div>":"Ga naar deze pagina <a href='{1}' target='_blank'>{1}</a> en type deze code : <mark>{0}</mark> <div class='altui-plugin-msg2'></div>",
	"{0} Tentative #{1}/10":"{0} Poging #{1}/10",
	"Failure after 10 tentatives, try again...":"Niet gelukt na 10 pogingen, probeer opnieuw...",
	"Select a Version":"Selecteer een versie","Edit Application Properties":"Bewerk applicatie eigenschappen",
	"Instructions":"Instructions","AllowMultiple":"AllowMultiple","AutoUpdate":"AutoUpdate",
	"Version Major":"Version Major","Version Minor":"Version Minor",
	"folders":"mappen",
	"release":"releasenaam",
	"Duration (sec or min-max)":"Duur (sec of min-max)",
	"Invalid Transition":"Ongeldige overgang",
	"Transition appears to be empty, you need at least a condition , a schedule or a timer":"Overgang lijkt leeg, minimaal één conditie vereist",
	"warning":"Waarschuwing",
	"Saving workflows":"Opslaan van workflows",
	"Smooth Link":"Smooth Link",
	"Show OS statistics in the footer":"Toon OS statistieken in de footer",
	"Show OS Statistics":"Toon OS statistieken",
	"TopStats:Show OS statistics in the footer":"TopStats:Toon OS statistieken in de footer",
	"Errors Warnings":"Fouten Waarschuwingen",
	"Next Page":"Volgende pagina","Prev Page":"Vorige pagina",
	"Zoom In":"Zoom +","Zoom Out":"Zoom -","Move Left":"Naar links","Move Right":"Naar rechts","Track Now":"Volgen",
	"My Home":"Mijn huis",
	"Sensors":"Sensoren",
	"Covers":"Covers",
	"Note: MyHome page is limited to 5 items per page for non registered users":"MijnHuis pagina is beperkt tot vijf items per pagina voor niet geregistreerde gebruikers",
	"Save the scene at least once before creating device watches":"Bewaar de scène minimaal één keer voor het maken van monitors",
	"Back":"Terug",
	"display or not the House mode widget on home page":"toon de House Modes widget op de startpagina wel of niet",
	"Show House Mode on home page":"Toon de House Mode op de startpagina",
	"ShowHouseMode:display or not the House mode widget on home page":"ShowHouseMode:toon de House Modes widget op de startpagina wel of niet",
	"Please be patient, registration will become effective after <mark>1 or 2 business days</mark>. Otherwise contact me with a copy of your page footer":"Geduld A.U.B, de registratie wordt effecttief na <mark1 of 2 kantoordagen</mark>. Zo niet, neem contact met mij op inclusief een kopie van de pagina footer",
	"Execute Action":"Aktie uitvoeren",
	"Start":"Start",
	"Cancel":"Cancel",
	"Force":"Forceer",
	"Muted":"Muted",
	"Unmuted":"Unmuted",
	"Pause":"Pauzeer",
	"Scene Trigger Evaluation mode":"Scene Trigger evaluatie modus",
	"Create From State":"Creër van Status"
});

// override rules with localized version
SpeechManager.initRules([
	{r:"(zet aan|schakelaar aan|open).*\\s+(%name%)", t:"device", a:{service:"urn:upnp-org:serviceId:SwitchPower1", action:"SetTarget", params:"{ \"newTargetValue\":1}"}},
	{r:"(zet uit|schakelaar uit|sluit).*\\s+(%name%)", t:"device", a:{service:"urn:upnp-org:serviceId:SwitchPower1", action:"SetTarget", params:"{ \"newTargetValue\":0}"}},
	{r:"(run|start).*\\s+(%name%)", t:"scene" },
	{r:"(toon|open).*\\s+(%name%)", t:"altui" },
	{r:"(toon|open).*\\s+(%name%)", t:"room" }
]);
