//# sourceURL=J_ALTUI_loc_it.js
// http://192.168.1.16:3480/data_request?id=lr_ALTUI_Handler&command=home
// This program is free software: you can redistribute it and/or modify
// it under the condition that it is for private or home useage and 
// this whole comment is reproduced in the source code file.
// Commercial utilisation is not authorized without the appropriate
// written agreement from amg0 / alexis . mermet @ gmail . com
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 

Localization.init( {
	"Home": "Casa",
	"Away":"Away",
	"Night":"Night",
	"Vacation":"Vacation",
	"Room": "Stanze",
	"Rooms": "Stanze",
	"Device":"Device",
	"Devices": "Dispositivi",
	"Control Panel": "Pannello di Controllo",
	"Scenes": "Scena",
	"Scene Edit": "Scena Modificare",
	"Plugins": "Plugins",
	"Custom Pages": "Pagine Personalizzate",
	"Edit Pages": "Modifica Pagine",
	"Credits": "Crediti",
	"LuaTest": "LuaTesy",
	"LuaStart": "LuaInizio",
	"Optimize": "Ottimizza",
	"Editor": "Editore",
	"Close":"Close",
	"Custom Pages Editor": "Pagine Personalizzate Editore",
	"Lua Startup": "Lua Avviare",
	"Lua Code Test":"Lua Codice Verificare",
	"Options": "Options",
	"Unmuted,Muted":"Normale,Muto",
	"Normal,Debug":"Normale,Debug",
	"Up":"Alza",
	"Stop":"Fermare",
	"Down":"Giù",
	"Open":"Apri",
	"Unlock,Lock":"Sbloccare,Serratura",
	"Bypass,Arm":"Free,Armata",
	"Use Custom Pages":"Pagine Usare Personalizzate",
	"Edit Custom Pages":"Modifica di Pagine Personalizzate",
	"More":"Più",
	"Less":"Less",
	"Remote Access Login":"Accesso Remoto Log",
	"Reload Luup Engine":"Ricaricare Luup Motore",
	"Lua Startup Code":"Lua Codice Avviamento",
	"Lua Test Code":"Avvio Codice Lua",
	"Localization":"Localizzazione",
	"Misc":"Vario",
	"Create":"Crea",
	"Runs in all modes, or in selected mode": "Runs in all modes, or in selected mode",
	"Run" : "Eseguire",
	"OFF,ON":"Spento,Acceso",
	"Working":"Lavorare",
	"Holiday":"Vacanze",
	"Wind":"Vento",
	"Are you sure you want to delete scene ({0})":"xxx",
	"Controller {0} is busy, be patient.":"Controller {0} is busy, be patient.",
	"Submit":"Submit",
	"Save Changes":"Save Changes",
	"Notification":"Notification",
	"Triggers":"Triggers",
	"Timers":"Timers",
	"Actions":"Actions",
	"Lua":"Lua",
	"OffLabel":"OffLabel",
	"OnLabel":"OnLabel",
	"Label":"Label",
	"Min":"Min",
	"Green":"Green",
	"Orange":"Orange",
	"Red":"Red",
	"Max":"Max",
	"Ticks":"Ticks",
	"TimerName":"TimerName",
	"TimerType":"TimerType",
	"TimerInterval":"TimerInterval",
	"TimerDayOfWeek":"TimerDayOfWeek",
	"TimerDayOfMonth":"TimerDayOfMonth",
	"TriggerName":"TriggerName",
	"Delay":"Delay",
	"Action to switch OFF":"Action to switch OFF",
	"Action to switch ON":"Action to switch ON",
	"Action":"Action",
	"Device Variable Properties":"Device Variable Properties",
	"Parameters":"Parameters",
	"Value":"Value",
	"Variable":"Variable",
	"Attributes":"Attributes",
	"Load":"Load",
	"Info":"Info",
	"Image":"Image",
	"Run Scene":"Run Scene",
	// "Edit":"xxx",
	// "Camera":"xxx",
	// "On Off":"xxx",
	// "Gauge":"xxx",
	// "Device Icon":"xxx",
	// "Scene":"xxx",
	// "Multi State":"xxx",
	// "Mo":"xxx",
	// "Tu":"xxx",
	// "We":"xxx",
	// "Th":"xxx",
	// "Fr":"xxx",
	// "Sa":"xxx",
	// "Su":"xxx",
	// "At a certain time of day":"xxx",
	// "At sunrise":"xxx",
	// "Before sunrise":"xxx",
	// "After sunrise":"xxx",
	// "At sunset":"xxx",
	// "Before sunset":"xxx",
	// "After sunset":"xxx",
	// "Timer":"xxx",
	// "**Illegal**":"xxx",
	// "interval":"xxx",
	// "day of week":"xxx",
	// "day of month":"xxx",
	// "absolute":"xxx",
	// "Search":"xxx",
	// "Remove":"xxx",
	// "No Match":"xxx",
	// "Reboot Vera":"xxx",
	"This plugin is a work in progress, it will continuously evolve over time.":"This plugin is a work in progress, it will continuously evolve over time.",
	"You may check out the evolutions on the Micasaverde <a href='http://forum.micasaverde.com/index.php/topic,30310.msg216129.html#msg216129'>Forum</a>":"You may check out the evolutions on the Micasaverde <a href='http://forum.micasaverde.com/index.php/topic,30310.msg216129.html#msg216129'>Forum</a>",
	// "All":"xxx",
	// "No Room":"xxx",
	// "Device creation failed":"xxx",
	// "Device {0} created successfully":"xxx {0} xxx",
	// "Filter":"xxx",
	// "Category":"xxx",
    "Could not create Room":"Could not create Room",
	"New Page":"New Page",
	"Page Properties":"Page Properties",
	"Delete this Page":"Delete this Page",
	"Save All Pages":"Save All Pages",
	"Files":"Fichiers",
	"Name":"Name",
	"Version":"Version",
	"Update":"Update",
	"Uninstall":"Uninstall",
	"Messages":"Messages",
	"zWave Network":"zWave Network",
	"ZWave":"ZWave",
	"Localize":"Localize",
	"Localizations":"Localizations",
	"Power Chart":"Power Chart",
	"Power":"Power",
	"Localization information":"Localization information",
	"Mesh":"Mesh",
	"Order By":"Order By",
	"Reset Poll Counters":"Reset Poll Counters",
	"Parent/Child Network":"Parent/Child Network","Parent/Child":"Parent/Child",
	"Drag and Drop to add/move/delete controls. use Ctrl+Click or lasso to select multiple controls":"Drag and Drop to add/move/delete controls. use Ctrl+Click or lasso to select multiple controls",
	"Drag and Drop to fix the position of a node. Simple Click to open or collapse a parent node, Shift Click to free a fixed node":"Drag and Drop to fix the position of a node. Simple Click to open or collapse a parent node, Shift Click to free a fixed node"	,
	"Network Quality":"Network Quality",
	"Quality":"Quality",
	"Show":"Show",
	"ZWave Routes":"ZWave Routes",
	"Scene Action Group":"Scene Action Group",
  "Pause Scene":"Pause Scene",
	"Trigger Restriction":"Trigger Restriction",
	"Restrict trigger based on certain times":"Restrict trigger based on certain times",
	"Start Time":"Start Time",
	"Stop Time":"Stop Time",
	"zWave Routes":"zWave Routes",
	"zWaveRoutes":"zWaveRoutes",
	"error happened during decoding triggers, probable duplicate ID or invalid format":"error happened during decoding triggers, probable duplicate ID or invalid format",
	"TblDevices":"TblDevices",
	"Table Devices":"Table Devices",
	"Update Neighbors":"Update Neighbors",
	"Update Neighbors succeeded":"Update Neighbors succeeded",
	"Copy to clipboard":"Copy to clipboard",
	"Data copied in clipboard":"Data copied in clipboard",
	"Code execution succeeded":"Code execution succeeded",
	"Code execution failed":"Code execution failed",
	"Reboot request succeeded":"Reboot request succeeded",
	"Reboot request failed":"Reboot request failed",
	"Favorite":"Favorite",
	"Favorites":"Favorites",
	"Variables":"Variables",
	"Used in":"Used in",
	"OsCommand":"OsCommand",
	"Disk Usage":"Disk Usage",
	"Free Space":"Free Space",
	"Plugin Files":"Plugin Files",
	"Log Sizes":"Log Sizes",
	"OS Command":"OS Command",
	"Frequent Commands":"Frequent Commands",
	"Output":"Output",
	"Os Command execution succeeded":"Os Command execution succeeded",
	"Version number or empty for latest official version":"Version number or empty for latest official version",
	"Update Plugin succeeded, be patient Luup will reload":"Update Plugin succeeded, be patient Luup will reload",
	"Enter a Vera OS ( Unix ) command, the stdout will be returned and displayed below":"Enter a Vera OS ( Unix ) command, the stdout will be returned and displayed below",
	"Os Command execution on vera failed.":"Os Command execution on vera failed.",
	"failed to execute":"failed to execute",
	"Are you Sure ?":"Are you Sure ?",
	"Yes":"Yes",
	"Are you sure you want to delete device ({0})":"Are you sure you want to delete device ({0})",
	"Are you sure you want to delete room":"Are you sure you want to delete room",
	"Are you sure you want to uninstall this plugin #{0} and all its created devices":"Are you sure you want to uninstall this plugin #{0} and all its created devices",
	"a newer version #{0} of ALTUI is available, do you want to upgrade ?":"a newer version #{0} of ALTUI is available, do you want to upgrade ?",
	"Question":"Question",
	"Options":"Options",
	"Show Video Thumbnail in Local mode":"Show Video Thumbnail in Local mode",
	"Cache Control":"Cache Control",
	"Custom Pages Control":"Custom Pages Control",
	"Refresh":"Refresh",
	"Search Logs":"Search Logs",
	"Tail Logs":"Tail Logs",
	"label":"label",
	"command":"command",
	"Add":"Add",
	"Default":"Default",
	"Command Parameters":"Command Parameters",
	"Parameter":"Parameter",
	"Test Code":"Test Code",
	"Panels":"Panels",
	"Reports":"Reports",
	"Evolutions":"Evolutions",
	"History":"History",
	"Date":"Date","Old":"Old","New":"New",
	"Scene History":"Scene History",
	"Button Label":"Button Label","Color":"Color",
	"Ran Scene #{0} successfully":"Ran Scene #{0} successfully",
	"Not used in scenes or workflows":"Not used in scenes or workflows",
	"Controller {0} did not respond":"Controller {0} did not respond",
	"Option":"Option",
	"Debug":"Debug",
	"All devices":"All devices",
	"One Device's States":"One Device's States",
	"Variable search":"Variable search",
	"Javascript code":"Javascript code",
	"Debug Tools":"Debug Tools",
	"Debug Actions":"Debug Actions",
	"Altui ID":"Altui ID",
	"Variable Name Pattern":"Variable Name Pattern",
	"an error happened during the execution":"an error happened during the execution",
	"Controller":"Controller",
	"Counters have been reset properly":"Counters have been reset properly",
	"do you want to change Lua startup code ? if yes, it will generate a Lua reload, be patient...":"do you want to change Lua startup code ? if yes, it will generate a Lua reload, be patient...",
	"Lua Startup code has been modified":"Lua Startup code has been modified",
	"Header":"Header",
	"Delay":"Delay",
	"Edited Scene {0} successfully":"Edited Scene {0} successfully",
	"Notification from {0}":"Notification from {0}",
	"Notify Users":"Notify Users",
	"Deleted Scene {0} successfully":"Deleted Scene {0} successfully",
	"Left Buttons are fixed on the page":"Left Buttons are fixed on the page",
	"See":"See",
	"2-columns Menu's limit":"2-columns Menu's limit",
	"Find Json":"Find Json",
	"Frame":"Frame",
	"Reload is done":"Reload is done",
	"Device Triggers":"Device Triggers",
	"Trigger":"Trigger",
	"Device Variable Watches":"Device Variable Watches",
	"Watch":"Watch",
	"Lua Expression with new=newvalue and old=oldvalue":"Lua Expression with new=newvalue and old=oldvalue",
	"Expression with old new as variables and lua operators like <  >  <= >= == ~=":"Expression with old new as variables and lua operators like <   >   <=  >=  ==  ~=",
	"Logs":"Logs",
	"Play":"Play",
	"Night,Day":"Night,Day",
	"Show Weather on home page":"Show Weather on home page",
	"Weather Temp Unit (UI5)":"Weather Temp Unit (UI5)",
	"Watch Formula":"Watch Formula","Generated code":"Generated code",
	"Edit Watch Expression":"Edit Watch Expression",
	"Return Result":"Return Result",
	"Console Output":"Console Output",
	"Lua execution succeeded":"Lua execution succeeded",
	"This test code will succeed if it is syntactically correct. It must be the body of a function and can return something. The return object and console output will be displayed)":"This test code will succeed if it is syntactically correct. It must be the body of a function and can return something. The return object and console output will be displayed)",
	"H M S part of a timestamp":"H M S part of a timestamp",
	"H M S duration in seconds":"H M S duration in seconds",
	"Convert text to number":"Convert text to number",
	"Welcome to ALTUI":"Benvenuti a VERA UI Alternativo",
	"Use Vera Favorites":"Use Vera Favorites",
	"Graph":"Graph",
	"Themes":"Themes",
	"Arm":"Arm",
	"Bypass":"Bypass",
	"Restart":"Restart",
	"On":"On","Off":"Off","Reset":"Reset",
	"Create Device succeeded":"Create Device succeeded",
	"Configuration":"Configuration",
	"Deleted Device {0} successfully":"Deleted Device {0} successfully",
	"Reset Theme Override":"Reset Theme Override",
	"Preview":"Preview",
	"Delete":"Delete",
	"Settings":"Settings",
	"Controllers":"Controllers",
	"Support":"Support",
	"TblScenes":"TblScenes",
	"TblControllers":"TblControllers",
	"TblWatches":"TblWatches",
	"Save":"Save",
	"Frame Properties":"Frame Properties",
	"Frame Label":"Frame Label",
	"background CSS":"background CSS",
	"IFrame Url":"IFrame Url",
	"Optional, if specified frame will be filled in with this url":"Optional, if specified frame will be filled in with this url",
	"Same Room for Devices/Scenes":"Same Room for Devices/Scenes",
	"Rules":"Rules",
	"Timeline":"Timeline",
	"Table Scenes":"Table Scenes",
	"Use new UI7 behavior for Heater devices":"Use new UI7 behavior for Heater devices",
	"Show all rows in grid tables":"Show all rows in grid tables",
	"Table Controllers":"Table Controllers",
	"Unregistered version for {0}":"Unregistered version for {0}",
	"Registered Version":"Registered Version",
	"Hide":"Hide",
	"Value ON":"Value ON",
	"Value OFF":"Value OFF",
	"Watches":"Watches",
	"Push to {5}":"Push to {5}",
	"Table Watches":"Table Watches",
	"Are you sure you want to delete scene watch ({0})":"Are you sure you want to delete scene watch ({0})",
	"Are you sure you want to delete data push ({0})":"Are you sure you want to delete data push ({0})",
	"Watch Display":"Watch Display","WatchDisplay":"WatchDisplay",
	"Alert - Camera":"Alert - Camera",
	"Workflows":"Workflows",
	"Workflow Pages":"Workflow Pages",
	"Workflow":"Workflow",
	"Test":"Test",
	"Workflow Editor":"Workflow Editor",
	"State":"State",
	"State Properties":"State Properties",
	"State Name":"State Name",
	"State Actions":"State Actions",
	"On Enter":"On Enter",
	"On Exit":"On Exit",
	"Link Properties":"Link Properties",
	"Link Name":"Link Name",
	"Link Conditions":"Link Conditions",
	"Conditions":"Conditions",
	"All conditions must match ( logical AND ) for the transition to happen":"All conditions must match ( logical AND ) for the transition to happen",
	"Timer Name":"Timer Name",
	"Duration":"Duration",
	"Distribute Horizontally":"Distribute Horizontally",
	"Distribute Vertically":"Distribute Vertically",
	"Slider":"Slider",
	"Workflow Report":"Workflow Report",
	"Upgrade Request succeeded, a Luup reload will happen":"Upgrade Request succeeded, a Luup reload will happen",
	"Invisible":"Invisible",
	"Battery":"Battery",
	"Zigbee":"Zigbee",
	"Bluetooth":"Bluetooth",
	"Pause Workflow":"Pause Workflow",
	"Report":"Report",
	"Copy":"Copy",
	"In Local access mode, show camera in video stream mode":"In Local access mode, show camera in video stream mode",
	"ShowVideoThumbnail:In Local access mode, show camera in video stream mode":"ShowVideoThumbnail:In Local access mode, show camera in video stream mode",
	"choose whether or not the selection Buttons on the left are scrolling with the page":"choose whether or not the selection Buttons on the left are scrolling with the page",
	"FixedLeftButtonBar:choose whether or not the selection Buttons on the left are scrolling with the page":"FixedLeftButtonBar:choose whether or not the selection Buttons on the left are scrolling with the page",
	"display or not the weather widget on home page":"display or not the weather widget on home page",
	"ShowWeather:display or not the weather widget on home page":"ShowWeather:display or not the weather widget on home page",
	"use the same favorites as set on your VERA box but prevent to have different favorites per client device":"use the same favorites as set on your VERA box but prevent to have different favorites per client device",
	"UseVeraFavorites:use the same favorites as set on your VERA box but prevent to have different favorites per client device":"UseVeraFavorites:use the same favorites as set on your VERA box but prevent to have different favorites per client device",
	"keep the same last selected room between the device and the scene pages":"keep the same last selected room between the device and the scene pages",
	"SyncLastRoom:keep the same last selected room between the device and the scene pages":"SyncLastRoom:keep the same last selected room between the device and the scene pages",
	"Fixes the footer at the bottom of the page but could have performance issues on mobile browsers":"Fixes the footer at the bottom of the page but could have performance issues on mobile browsers",
	"Sticky Footer to bottom":"Sticky Footer to bottom",
	"StickyFooter:Fixes the footer at the bottom of the page but could have performance issues on mobile browsers":"StickyFooter:Fixes the footer at the bottom of the page but could have performance issues on mobile browsers",
	"technical option to trigger the UI7 behavior for heater":"technical option to trigger the UI7 behavior for heater",
	"UseUI7Heater:technical option to trigger the UI7 behavior for heater":"UseUI7Heater:technical option to trigger the UI7 behavior for heater",
	"allways show all the lines in the grid tables, or have a row count selector instead":"allways show all the lines in the grid tables, or have a row count selector instead",
	"ShowAllRows:allways show all the lines in the grid tables, or have a row count selector instead":"ShowAllRows:allways show all the lines in the grid tables, or have a row count selector instead",
	"if a menu has more entries than this number then show the menu entries in 2 columns":"if a menu has more entries than this number then show the menu entries in 2 columns",
	"Menu2ColumnLimit:if a menu has more entries than this number then show the menu entries in 2 columns":"Menu2ColumnLimit:if a menu has more entries than this number then show the menu entries in 2 columns",
	"Unit for temperature":"Unit for temperature",
	"TempUnitOverride:Unit for temperature":"TempUnitOverride:Unit for temperature",
	"Editor Control":"Editor Control",
	"Editor Theme":"Editor Theme",
	"Editor font size in pixels":"Editor font size in pixels",
	"Editor Font Size":"Editor Font Size",
	"EditorFontSize:Editor font size in pixels":"EditorFontSize:Editor font size in pixels",
	"info":"info",
	"Bag":"Bag",
	"Import/Export":"Import/Export",
	"Variables Bag":"Variables Bag",
	"No data to display":"No data to display",
	"Schedules":"Schedules",
	"Duration (sec)":"Duration (sec)",
	"None":"None",
	"Only in the following mode(s)":"Only in the following mode(s)",
	"Record":"Record",
	"Normal,Recorder":"Normal,Recorder",
	"Are you sure you want to modify this attribute":"Are you sure you want to modify this attribute",
	"Check for Updates":"Check for Updates",
	"License Fees":"License Fees",
	"License":"License",
	"Horizontal Slider":"Horizontal Slider",
	"For non commercial use, ALTUI plugin is free for trial with some limitation on its functionality. To compensate the effort and time spent on regularly improving this project, a registration fee equivalent to <span class='text-info'><mark><b>2€ per month</b></mark></span> is requested for longer term use. You can choose your level of contribution.":"For non commercial use, ALTUI plugin is free for trial with some limitation on its functionality. To compensate the effort and time spent on regularly improving this project, a registration fee equivalent to <span class='text-info'><mark><b>2€ per month</b></mark></span> is requested for longer term use. You can choose your level of contribution.",
	"Once registered you will get:<ul><li>Access to all the releases and auto update mechanism (not available to non registered users)</li><li>Removal of unregistered welcome message, as well as license message in the footer</li></ul>":"Once registered you will get:<ul><li>Access to all the releases and auto update mechanism (not available to non registered users)</li><li>Removal of unregistered welcome message, as well as license message in the footer</li></ul>",
	"Resellers or Integrators are welcome to contact me for eventual commercial agreements.":"Resellers or Integrators are welcome to contact me for eventual commercial agreements.",
	"Check for Updates":"Check for Updates",
	"Unregistered Version":"Unregistered Version",
	"active":"active",
	"Device zWave Parameters":"Paramètres module zWave",
	"Lua Editor":"Éditeur Lua",
	"Recording...":"Enregistrement...",
	"Close for 24h":"Fermer pour 24h",
	"Backup Controller":"Backup Controller",
	"ZWave Heal":"ZWave Heal",
	"ZWave Inclusion":"ZWave Inclusion",
	"ZWave Exclusion":"ZWave Exclusion",
	"Details":"Details",
	"You already have the latest version":"You already have the latest version",
	"Prevent drag and drop of favorites to reorder them":"Prevent drag and drop of favorites to reorder them",
	"Lock favorites position":"Lock favorites position",
	"LockFavoritePosition:Prevent drag and drop of favorites to reorder them":"LockFavoritePosition:Prevent drag and drop of favorites to reorder them",
	"Top":"Top","Page Up":"Page Up","Page Down":"Page Down","Bottom":"Bottom",
	"App Store":"App Store","Publish App":"Publish App","Install":"Install","Application Store":"Application Store",
	"Publish":"Publish","ALT":"ALT","Vera":"Vera","Publish Application":"Publish Application",
	"Contacting Server...":"Contacting Server...",
	"Please go to this page <a href='{1}' target='_blank'>{1}</a> and enter this code : {0}":"Please go to this page <a href='{1}' target='_blank'>{1}</a> and enter this code : {0}",
	"Select an App":"Select an App","Publish an App":"Publish an App",
	"Application":"Application","App ID":"App ID","App Title":"App Title",
	"VersionMajor":"VersionMajor","VersionMinor":"VersionMinor","Description":"Description",
	"Icon":"Icon","DeviceFileName":"DeviceFileName","DeviceType":"DeviceType","ImplFile":"ImplFile",
	"GitHub":"GitHub","backup":"backup","default":"default","downloads":"downloads",
	"pattern":"pattern","source":"source","Vera Store":"Vera Store","version":"version","Modify":"Modify",
	"Refreshing Token...":"Refreshing Token...","Authenticating client device...":"Authenticating client device...",
	"Please go to this page <a href='{1}' target='_blank'>{1}</a> and enter this code : <mark>{0}</mark> <div class='altui-plugin-msg2'></div>":"Please go to this page <a href='{1}' target='_blank'>{1}</a> and enter this code : <mark>{0}</mark> <div class='altui-plugin-msg2'></div>",
	"{0} Tentative #{1}/10":"{0} Tentative #{1}/10",
	"Failure after 10 tentatives, try again...":"Failure after 10 tentatives, try again...",
	"Select a Version":"Select a Version","Edit Application Properties":"Edit Application Properties",
	"Instructions":"Instructions","AllowMultiple":"AllowMultiple","AutoUpdate":"AutoUpdate",
	"Version Major":"Version Major","Version Minor":"Version Minor",
	"folders":"folders",
	"release":"release",
	"Duration (sec or min-max)":"Duration (sec or min-max)",
	"Invalid Transition":"Invalid Transition",
	"Transition appears to be empty, you need at least a condition , a schedule or a timer":"Transition appears to be empty, you need at least a condition , a schedule or a timer",
	"warning":"warning",
	"Saving workflows":"Saving workflows",
	"Smooth Link":"Smooth Link",
	"Show OS statistics in the footer":"Show OS statistics in the footer",
	"Show OS Statistics":"Show OS Statistics",
	"TopStats:Show OS statistics in the footer":"TopStats:Show OS statistics in the footer",
	"Next Page":"Next Page","Prev Page":"Prev Page",
	"Zoom In":"Zoom In","Zoom Out":"Zoom Out","Move Left":"Move Left","Move Right":"Move Right","Track Now":"Track Now",
	"My Home":"My Home",
	"Sensors":"Sensors",
	"Covers":"Covers",
	"Note: MyHome page is limited to 5 items per page for non registered users":"Note: MyHome page is limited to 5 items per page for non registered users",
	"Save the scene at least once before creating device watches":"Save the scene at least once before creating device watches",
	"Back":"Back",
	"display or not the House mode widget on home page":"display or not the House mode widget on home page",
	"Show House Mode on home page":"Show House Mode on home page",
	"ShowHouseMode:display or not the House mode widget on home page":"ShowHouseMode:display or not the House mode widget on home page",
	"Please be patient, registration will become effective after <mark>1 or 2 business days</mark>. Otherwise contact me with a copy of your page footer":"Please be patient, registration will become effective after <mark>1 or 2 business days</mark>. Otherwise contact me with a copy of your page footer",
	"Execute Action":"Execute Action",
	"Start":"Start",
	"Cancel":"Cancel",
	"Force":"Force",
	"Muted":"Muted",
	"Unmuted":"Unmuted",
	"Pause":"Pause",
	"Scene Trigger Evaluation mode":"Scene Trigger Evaluation mode",
	"Create From State":"Create From State",
	"Search Results":"Search Results"
});

// override rules with localized version
SpeechManager.initRules([
	{r:"(switch on|turn on|open).*\\s+(%name%)", t:"device", a:{service:"urn:upnp-org:serviceId:SwitchPower1", action:"SetTarget", params:"{ \"newTargetValue\":1}"}},
	{r:"(switch off|turn off|close).*\\s+(%name%)", t:"device", a:{service:"urn:upnp-org:serviceId:SwitchPower1", action:"SetTarget", params:"{ \"newTargetValue\":0}"}},
	{r:"(run|launch).*\\s+(%name%)", t:"scene" },
	{r:"(show|open).*\\s+(%name%)", t:"altui" },
	{r:"(show|open).*\\s+(%name%)", t:"room" }
]);	
		

